### ISSUE TITLE
Magento 2.1 compatibility

### ISSUE THREAD

**Issue by anvanza** [fastly/fastly-magento2#10]
I tried to install the plugin using composer on a Magento 2.1.0 installation but I noticed it's incompatible.

  Problem 1
    - Conclusion: don't install fastly/magento2 1.0.4
    - Conclusion: don't install fastly/magento2 1.0.3
    - Conclusion: don't install fastly/magento2 1.0.2
    - Conclusion: don't install fastly/magento2 1.0.1
    - Conclusion: don't install fastly/magento2 1.0.0|remove magento/framework 100.1.0
    - Conclusion: don't install fastly/magento2 1.0.0|don't install magento/framework 100.1.0
    - Installation request for fastly/magento2 ^1.0 -> satisfiable by fastly/magento2[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].
    - fastly/magento2 1.0.0 requires magento/framework 100.0.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - Can only install one of: magento/framework[100.1.0, 100.0.2].
    - Can only install one of: magento/framework[100.1.0, 100.0.3].
    - Can only install one of: magento/framework[100.1.0, 100.0.4].
    - Can only install one of: magento/framework[100.1.0, 100.0.5].
    - Can only install one of: magento/framework[100.1.0, 100.0.6].
    - Can only install one of: magento/framework[100.1.0, 100.0.7].
    - Can only install one of: magento/framework[100.1.0, 100.0.8].
    - Can only install one of: magento/framework[100.1.0, 100.0.9].
    - Installation request for magento/framework (locked at 100.1.0) -> satisfiable by magento/framework[100.1.0].

**Comment by phoenix-bjoern** [comment]
@anvanza Can you please try again with the new version 1.0.5 ?
