### ISSUE TITLE
Please tag version 1.2.33

### ISSUE THREAD

**Issue by hostep** [fastly/fastly-magento2#113]
Hi all

Magento starts showing notifications that version 1.2.33 is out, but running `composer update` doesn't find this new version yet. I think you guys forgot to [tag](https://github.com/fastly/fastly-magento2/releases) a new version?

Thanks!

**Comment by vvuksan** [comment]
Sorry about that.

**Comment by hostep** [comment]
No problem, it works now, thanks! :)

**Comment by hostep** [comment]
@vvuksan: same thing with version 1.2.34 now :p
Magento gives notice about 1.2.34 but composer doesn't see it yet.

It might be a good idea to write some kind of "publishing script" which executes all the steps every time a new version gets released? Just an idea ... :)

**Comment by vvuksan** [comment]
Yeah I have not tagged it yet as there are couple more steps I need to do before releasing and I update the version as soon as I commit new code to avoid new code showing up under an old version.

**Comment by vvuksan** [comment]
Fascinating though that Magento notices it so quickly :-/

**Comment by hostep** [comment]
Indeed, I wonder where Magento gets this version from?

**Comment by vvuksan** [comment]
It's our module that fetches

https://github.com/fastly/fastly-magento2/blob/master/composer.json

and verifies against a local version however I thought that ran once a day or so.

**Comment by hostep** [comment]
@vvuksan, it would also be appreciated to only see one notification per new module version, it's getting a bit too spammy to my liking ;)

<img width="791" alt="screen shot 2017-11-24 at 09 44 35" src="https://user-images.githubusercontent.com/85479/33202255-3150d876-d0fc-11e7-8d02-99c928d8f440.png">
