### ISSUE TITLE
ESI is not present in the HTML output. This is just a warning.

### ISSUE THREAD

**Issue by ramdasbalwad** [fastly/fastly-magento2#119]
I am not able to find the reason here why this is not working, I am using the M2 EE version 2.1.8 and updated the latest fastly version but still it shows me ESI is not present in the HTML output. This is just a warning.

What will be the best way to resolve this ?

**Comment by vvuksan** [comment]
It is possible you do not have ESIs at all. Perhaps it's best if you open up a ticket with our support to look into the specific issue.
