### ISSUE TITLE
Packagist or Magento Marketplace

### ISSUE THREAD

**Issue by anvanza** [fastly/fastly-magento2#12]
Why is the module not published to packagist or the Magento Marketplace?
This would make the installation just a bit easier.

**Comment by jondade** [comment]
It is published to the Magento Marketplace, but is due an updated version. You can see it [here](https://marketplace.magento.com/fastly-magento2.html).

I'll look into adding this to packagist, but can't promise when this will happen.

**Comment by vvuksan** [comment]
This has now been done
