### ISSUE TITLE
Latest Version Purge all Error

### ISSUE THREAD

**Issue by jordanvector** [fastly/fastly-magento2#141]
After the latest fastly release I am getting a 500 error when doing a purge all from the backend.  I am on a pro tier of magento cloud as an environment.  Here is the stack trace:

Error: Uncaught exception 'Error' with message 'Call to a member function getAvailableTypes() on null' in /app/7alebf6ygqtlm/vendor/fastly/magento2/Controller/Adminhtml/FastlyCdn/Purge/All.php:67
in Fastly\Cdn\Controller\Adminhtml\FastlyCdn\Purge\All::execute called at /app/7alebf6ygqtlm/vendor/magento/framework/App/Action/Action.php (107)
in Magento\Framework\App\Action\Action::dispatch called at /app/7alebf6ygqtlm/vendor/magento/module-backend/App/AbstractAction.php (229)
in Magento\Backend\App\AbstractAction::dispatch called at /app/7alebf6ygqtlm/vendor/magento/framework/Interception/Interceptor.php (58)
in Fastly\Cdn\Controller\Adminhtml\FastlyCdn\Purge\All\Interceptor::___callParent called at /app/7alebf6ygqtlm/vendor/magento/framework/Interception/Interceptor.php (138)
in Fastly\Cdn\Controller\Adminhtml\FastlyCdn\Purge\All\Interceptor::Magento\Framework\Interception\{closure} called at /app/7alebf6ygqtlm/vendor/magento/module-backend/App/Action/Plugin/Authentication.php (143)
in Magento\Backend\App\Action\Plugin\Authentication::aroundDispatch called at /app/7alebf6ygqtlm/vendor/magento/framework/Interception/Interceptor.php (135)
in Fastly\Cdn\Controller\Adminhtml\FastlyCdn\Purge\All\Interceptor::Magento\Framework\Interception\{closure} called at /app/7alebf6ygqtlm/vendor/magento/framework/Interception/Interceptor.php (153)
in Fastly\Cdn\Controller\Adminhtml\FastlyCdn\Purge\All\Interceptor::___callPlugins called at /app/7alebf6ygqtlm/generated/code/Fastly/Cdn/Controller/Adminhtml/FastlyCdn/Purge/All/Interceptor.php (26)
in Fastly\Cdn\Controller\Adminhtml\FastlyCdn\Purge\All\Interceptor::dispatch called at /app/7alebf6ygqtlm/vendor/magento/framework/App/FrontController.php (55)
in Magento\Framework\App\FrontController::dispatch called at /app/7alebf6ygqtlm/vendor/magento/framework/Interception/Interceptor.php (58)
in Magento\Framework\App\FrontController\Interceptor::___callParent called at /app/7alebf6ygqtlm/vendor/magento/framework/Interception/Interceptor.php (138)
in Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure} called at ? (?)
in call_user_func_array called at /app/7alebf6ygqtlm/vendor/m2e/ebay-amazon-magento2/Plugin/AbstractPlugin.php (34)
in Ess\M2ePro\Plugin\AbstractPlugin::execute called at /app/7alebf6ygqtlm/vendor/m2e/ebay-amazon-magento2/Plugin/HealthStatus/Magento/Framework/App/FrontController.php (42)
in Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController::aroundDispatch called at /app/7alebf6ygqtlm/vendor/magento/framework/Interception/Interceptor.php (135)
in Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure} called at /app/7alebf6ygqtlm/vendor/magento/framework/Interception/Interceptor.php (153)
in Magento\Framework\App\FrontController\Interceptor::___callPlugins called at /app/7alebf6ygqtlm/generated/code/Magento/Framework/App/FrontController/Interceptor.php (26)
in Magento\Framework\App\FrontController\Interceptor::dispatch called at /app/7alebf6ygqtlm/vendor/magento/framework/App/Http.php (135)
in Magento\Framework\App\Http::launch called at /app/7alebf6ygqtlm/generated/code/Magento/Framework/App/Http/Interceptor.php (24)
in Magento\Framework\App\Http\Interceptor::launch called at /app/7alebf6ygqtlm/vendor/magento/framework/App/Bootstrap.php (256)
in Magento\Framework\App\Bootstrap::run called at /app/7alebf6ygqtlm/pub/index.php (37)

**Comment by vvuksan** [comment]
@jordanvector we are investigating. I would recommend downgrading to 1.2.41 until we have a patch in place.

**Comment by jordanvector** [comment]
@vvuksan heard that.  Will do

**Comment by vvuksan** [comment]
@jordanvector this is fixed in 1.2.43. Let us know if it doesn't fix the issue for you.
