### ISSUE TITLE
[BUG] Magento 2 system configuration tab broken

### ISSUE THREAD

**Issue by aleksandrosadchiy** [fastly/fastly-magento2#151]
Bug:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Failed to check Service details.

Exception #0 (Magento\Framework\Exception\LocalizedException): Failed to check Service details.
#0 /var/www/html/vendor/fastly/magento2/Model/Config/Backend/ListAcl.php(48): Fastly\Cdn\Model\Api->checkServiceDetails()
#1 /var/www/html/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(458): Fastly\Cdn\Model\Config\Backend\ListAcl->toOptionArray(true)
#2 /var/www/html/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(376): Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel(Object(Fastly\Cdn\Model\Config\Backend\ListAcl))

Added in since 1.2.43 by @tnikcevs
fastly/magento2/Model/Api.php

`
```
public function checkServiceDetails($test = false, $serviceId = null, $apiKey = null)
    {
        if (!$test) {
            $uri = rtrim($this->_getApiServiceUri(), '/');
            $result = $this->_fetch($uri);
        } else {
            $uri = $this->config->getApiEndpoint() . 'service/' . $serviceId;
            $result = $this->_fetch($uri, \Zend_Http_Client::GET, null, true, $apiKey);
        }

        if (!$result) {
            throw new LocalizedException(__('Failed to check Service details.'));
        }

        return $result;
    }
```
`
additional check breaks tab

Added by:
https://github.com/fastly/fastly-magento2/commit/f7ee285ddf030845fa78034fa8ea9d8ea1b5fdcf

**Comment by vvuksan** [comment]
Fixed in #152
