### ISSUE TITLE
"At least one device pixel ratio must be selected" error shows up even when Fastly isn't enabled

### ISSUE THREAD

**Issue by hostep** [fastly/fastly-magento2#162]
Hi guys

I'm trying to save a configuration value in the Advanced => System section (unrelated to Fastly), but while doing so, I get the error `At least one device pixel ratio must be selected.`. Even though Fastly has never been configured on that environment.
This is on an 'integration' environment of the Magento Cloud, and we can't use Fastly over there, so it makes no sense that we try to configure it.

We are using Magento 2.2.2 and `fastly/magento2` version 1.2.48

Thanks!

**Comment by vvuksan** [comment]
Fixed in #164
