### ISSUE TITLE
Composer install fails with 'Plugin class Fastly\Cdn\Model\PageCache\ConfigPlugin doesn't exist'

### ISSUE THREAD

**Issue by jondade** [fastly/fastly-magento2#17]
PHP version 5.6
Composer version 1.2.0
Magento version 2.0.8 EE
Fastly module version 1.0.5

Error message: `Plugin class Fastly\Cdn\Model\PageCache\ConfigPlugin doesn't exist`

Steps to repro:
Follow instructions for installing using composer up to `bin/magento module:enable Fastly_Cdn`.
When running `bin/magento setup:upgrade` or `bin/magento cache:clean` the error message above is displayed.

**Comment by phoenix-bjoern** [comment]
@jondade Please check out the latest version 1.0.8. This fixed in #8 should fix this problem.

**Comment by vvuksan** [comment]
This is a bug in Magento Core. It has been reported to Magento and will be addressed in the next release.
