### ISSUE TITLE
Can't uninstall the module in 2.2 using Web Setup Wizard

### ISSUE THREAD

**Issue by vvuksan** [fastly/fastly-magento2#180]
Pasting this from a internal Fastly ticket

Only steps we have taken is using the Web Setup Wizard in Magento. In the last step nothing happens, the console log stays empty even after more than an hour.

**Comment by deninchoo** [comment]
Hi @vvuksan 

I can't reproduce this issue. The extension gets successfully uninstalled for me. Would it be possible to get the exact Magento 2 and Fastly versions where this happens?
