### ISSUE TITLE
Disabling Magento_Review causes Fastly module enablement to fail

### ISSUE THREAD

**Issue by vvuksan** [fastly/fastly-magento2#185]
Question that was posted on IRC

```
So, question for anyone familiar with Fastly and Magento 2.  I'm attempting to install it on an environment with Magento_Review disabled.   Attempting to enable Fastly throws this error:

Unable to change status of modules because of the following constraints:
Cannot enable Fastly_Cdn because it depends on disabled modules:
Magento_Review: Fastly_Cdn->Magento_Config->Magento_Backend->Magento_Reports->Magento_Review
However, I can't find anything demonstrating that this dependency is needed, or even declared
```

**Comment by Sanfam** [comment]
I was just about to open this exact same issue following my attempt to implement Fastly on an environment with Magento_Review disabled.  In our use case, we have opted to use Yotpo to manage all product reviews in place of Magento's stock review functionality.

As with @vvuksan , I'm unable to find anything which declares this.

**Comment by Sanfam** [comment]
Please close this issue as it is not a Fastly problem but an environmental issue.  

Thanks to the help of @vvuksan, it has been found that this is a side-effect of our store's upgrade path. 
 During the upgrade from 2.0 to 2.1 to 2.1.7, this module became more closely intertwined with core and is now a dependency of `module_store`, itself a dependency of Fastly.  This didn't stop us from upgrading to this point but will stop us from pushing further forward, and does suggest that the correct solution in this case is to reactivate `Magento_Review`.
