### ISSUE TITLE
magento 2.2.x multi domain for multi store view

### ISSUE THREAD

**Issue by springerin** [fastly/fastly-magento2#187]
Doesn't seem to be handled the case when using different domain per store view or am I missing some configuration?

**Comment by vvuksan** [comment]
Can you tell us what you have tried ?

**Comment by springerin** [comment]
So the steps I did are:
install the module
enable the module as per documentation
added the first domain and verified
connected this domain with fastly with the service id and token
all worked fine
added a second domain and verified
went to configure this as well but when I select the store view of the second domain, I can't see any configuration setting in the backend leaving with only one service to be added and setted per instance of magento. I may be missing something on this but how do we add the second domain to be connected with fastly through magento and so to flush accordingly etc etc....

**Comment by vvuksan** [comment]
By default Fastly takes requested HTTP hostname into account when caching and we pass the requested Host header to your backend so as long as your Magento backend is set up with these domain names it should just work. As far as flushing is concerned Magento will mark all documents with their own tags so this should not be a problem either.

**Comment by deninchoo** [comment]
At the moment, the fastly-magento2 module only supports a single Fastly Service and it's configuration, ie. different store views can not have different Fastly Services configured. A single Fastly Service can have multiple domains set up in the Fastly web interface; however, flushing catalog images, JS, CSS and static file caches will be done for the entire Magento instance while the Magento generated content can be cleared for each store view from within the Magento configuration.

**Comment by springerin** [comment]
ok, many thanks to both.
