### ISSUE TITLE
FilesystemIterator::__construct(/var/www/html/var/vcl_snippets_custom/): failed to open dir: No such file or directory

### ISSUE THREAD

**Issue by springerin** [fastly/fastly-magento2#191]
Magento 2.2.3
Upgrade from 1.2.57 to 1.2.58
Upload VLC generates FilesystemIterator::__construct(/var/www/html/var/vcl_snippets_custom/): failed to open dir: No such file or directory
Returning to 1.2.57 works fine

**Comment by vvuksan** [comment]
We'll look into it. Thanks for reporting.

**Comment by vvuksan** [comment]
Fix has been included in 1.2.59. Let us know if you still see an issue.

**Comment by springerin** [comment]
I confirm on 1.2.59 is solved.
