### ISSUE TITLE
Geoip redirect on wrong store after click ok in popup magento 2.2.6

### ISSUE THREAD

**Issue by mackendy** [fastly/fastly-magento2#220]
With the 2.2.6 version of Magento, when we activate the Geoip, after click on the ok button to be redirected on the good store, the redirection was broken we stay on the same store. the path "store/store/switch" change in 2.2.6 and don't work in the same way.

**Comment by vvuksan** [comment]
We'll look into it.

**Comment by vvuksan** [comment]
Should be fixed with #227. It was rolled in version 1.2.75.
