### ISSUE TITLE
The module breaks search engine switcher in the backend.

### ISSUE THREAD

**Issue by iskliarenko** [fastly/fastly-magento2#221]
Hello Fastly team,

**Summary of issue**
It is impossible to switch search engine with installed Fastly_Cdn module via Magento backend

**Steps to replicate**
1. Install Fastly module (latest version) on the latest Magento (2.2.6), no needs to enable FastlyCDN as FPC engine.
2. Go to Stores > Configuration > Catalog > Catalog Search, uncheck 'Use default' near 'Search Engine', select 'ElasticSearch' and press 'Test Connection' button.
3. Notice the button doesn't work.
4. Turn off the module:
`php bin/magento module:disable Fastly_Cdn`
Repeat the second step - now 'Test Connection' button is working fine.

<img width="450" alt="screen shot 2018-10-31 at 12 05 07 pm" src="https://user-images.githubusercontent.com/10883371/47780984-4b239c00-dd05-11e8-8e11-e8dc4da3d408.png">

**Comment by vvuksan** [comment]
We are investigating.

**Comment by vvuksan** [comment]
Hi @iskliarenko,

Can you upgrade to 1.2.75 and see if the issue has been fixed.

**Comment by iskliarenko** [comment]
Yes, the button works fine in 1.2.75. Thank you!
