### ISSUE TITLE
Requested country is not available.

### ISSUE THREAD

**Issue by RDXSportsCom** [fastly/fastly-magento2#225]
I just installed fastly v1.0.12 on Magento EC 2.2.5 and getting following error in admin panel config section

> 1 exception(s):
> Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested country is not available.
> 
> /public_html/vendor/fastly/magento2/Model/Statistic.php(359): Magento\Directory\Model\CountryInformationAcquirer->getCountryInfo('GB')

**Comment by vvuksan** [comment]
Fastly v1.0.12 is an ancient version. Can you install our latest version which is 1.2.75.

**Comment by RDXSportsCom** [comment]
How I can install 1.2.75 as I have nothing found on composer update in Magento 2.2.5.

**Comment by aleksandrosadchiy** [comment]
**Issue**
Error during 'Save Config' operation with added to  Fastly config credentials

**Steps To Reproduce the issue**
1. Magento 2.2.2 or Magento 2.2.6 installed
2. Fastly 1.2.74 installed
3. Set Admin Panel -> Stores->Settings->Configuration->General->General->Default Country = US
4. Admin Panel -> Stores->Settings->Configuration->General->General->Allow Countries = US (Only <img width="1093" alt="screen shot 2018-11-08 at 16 34 43" src="https://user-images.githubusercontent.com/9470871/48205116-464d9080-e374-11e8-9fcb-7edae1f1c256.png">
5. Admin Panel -> Stores->Settings->Configuration->General->General->Store Information -> Country = GB 
<img width="1005" alt="screen shot 2018-11-08 at 16 36 32" src="https://user-images.githubusercontent.com/9470871/48205212-801e9700-e374-11e8-9d1b-60050a85189e.png">
6. Admin Panel -> Stores->Settings->Configuration->Advanced->System->Full Page Cache-> Choose Fastly
7. Add anyting to fields Fastly API Token and  Fastly Service ID
8. Click 'Save Config'

**Expected Result**
Config Saved

**Actual Result**
On Magento 2.2.2 error looks like:
`1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested country is not available.

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested country is not available.
#0 /mnt/data/home/oosadchyi/dev/pfqoyvxdosy24/vendor/fastly/magento2/Model/Statistic.php(359): Magento\Directory\Model\CountryInformationAcquirer->getCountryInfo('GB')
#1 /mnt/data/home/oosadchyi/dev/pfqoyvxdosy24/vendor/fastly/magento2/Model/Statistic.php(320): Fastly\Cdn\Model\Statistic->getSiteLocation()
#2 /mnt/data/home/oosadchyi/dev/pfqoyvxdosy24/vendor/fastly/magento2/Model/Statistic.php(253): Fastly\Cdn\Model\Statistic->prepareCustomVariables()
#3 /mnt/data/home/oosadchyi/dev/pfqoyvxdosy24/vendor/fastly/magento2/Model/Statistic.php(419): Fastly\Cdn\Model\Statistic->prepareGAReqData()
#4 /mnt/data/home/oosadchyi/dev/pfqoyvxdosy24/vendor/fastly/magento2/Model/Statistic.php(586): Fastly\Cdn\Model\Statistic->getGAReqData()
#5 /mnt/data/home/oosadchyi/dev/pfqoyvxdosy24/vendor/fastly/magento2/Model/Statistic.php(504): Fastly\Cdn\Model\Statistic->sendReqToGA(Array)`

On 2.2.6 the same error message but admin panel works
<img width="1559" alt="screen shot 2018-11-08 at 16 29 31" src="https://user-images.githubusercontent.com/9470871/48205582-210d5200-e375-11e8-8603-987216e51ac6.png">

**Comment by vvuksan** [comment]
Hi @RDXSportsCom ,

can you use composer to install the latest dev version ie.

composer require fastly/magento2 dev-master

and let me know if that fixes the issue you are seeing
