### ISSUE TITLE
Latest Version Overlay Actions No longer work

### ISSUE THREAD

**Issue by jordanvector** [fastly/fastly-magento2#229]
In the latest release I noticed that the overlay.js file that typically was used for the actions overlay when 404's in the fastly section.  Because of that I can no longer update the fastly vcl snippet from the backend, update backend settings, and anything else that depends on the overlay.  Any idea how I can fix this?

Steps to reproduce.

Click upload VCL to fastly button, overlay is supposed to slide out from the left but nothing happens

**Comment by vvuksan** [comment]
Hi @jordanvector how did you update the module as I am unable to reproduce the issue.

**Comment by jordanvector** [comment]
composer update.  Look at the lock file I am on "version": "1.2.75",

**Comment by vvuksan** [comment]
Indeed it was renamed. Did you run 

```magento setup:upgrade
magento cache:clean
```

?

**Comment by jordanvector** [comment]
Yeah did both, we are on magento cloud so that does that during the deployment step

**Comment by vvuksan** [comment]
Can you try latest version ie 1.2.76 to see if it's still happening?

**Comment by jordanvector** [comment]
Perfect, bumping the version the overlay now works.  Thank you very much
