### ISSUE TITLE
saving configuration throws fatal error

### ISSUE THREAD

**Issue by valugi** [fastly/fastly-magento2#234]
Hi guys,
I have installed the Fastly_Cdn Magento2 module and everything seems fine. I get the option to activate and testing the Fastly Credentials works fine.

But I get this error when I try to save the configuration. 
My version of Magento is 2.2.3 and Fastly_Cdn is 1.2.77.

Any suggestions?

` PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Config\Model\Config\Structure\Element\Field\Interceptor::shouldCloneFields() in /var/www/magento2/vendor/magento/module-config/Model/Config.php:212
Stack trace:
#0 /var/www/magento2/vendor/magento/module-config/Model/Config.php(312): Magento\Config\Model\Config->_processGroup('template', Array, Array, 'system/cron', Array, Array, Object(Magento\Framework\DB\Transaction), Object(Magento\Framework\DB\Transaction))
#1 /var/www/magento2/vendor/magento/module-config/Model/Config.php(146): Magento\Config\Model\Config->_processGroup('cron', Array, Array, 'system', Array, Array, Object(Magento\Framework\DB\Transaction), Object(Magento\Framework\DB\Transaction))
#2 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Model\Config->save()
#3 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Model\Config\Interceptor->___callParent('save', Array)
#4 /var/www/magento2/vendor/magento/framework/ in /var/www/magento2/vendor/magento/module-config/Model/Config.php on line 212`

**Comment by deninchoo** [comment]
Hi @valugi , can you make sure that the **system.xml** and **crontab.xml** files in your project all have unique group IDs and that they don't contain any extra characters that shouldn't be in a group ID or somewhere else in those files.

**Comment by valugi** [comment]
Hi @deninchoo,
Thanks for your suggestion. As you know there are hundreds of system.xml and crontab.xml that are getting merged and my installation worked fine so far. 

I was trying to find the called class and I cannot find it in Magento code:

> Magento\Config\Model\Config\Structure\Element\Field\Interceptor

`
$ ls -lat vendor/magento/module-config/Model/Config/Structure/Element/
total 40
-rwxrwxr-x. 1 php-fpm php-fpm  2142 Dec 13 16:41 AbstractComposite.php
drwxrwxr-x. 2 php-fpm php-fpm    65 Dec 13 16:41 Dependency
-rwxrwxr-x. 1 php-fpm php-fpm 13386 Dec 13 16:41 Field.php
-rwxrwxr-x. 1 php-fpm php-fpm  1204 Dec 13 16:41 FlyweightFactory.php
drwxrwxr-x. 2 php-fpm php-fpm    23 Dec 13 16:41 Group
-rwxrwxr-x. 1 php-fpm php-fpm  3716 Dec 13 16:41 Group.php
drwxrwxr-x. 2 php-fpm php-fpm    74 Dec 13 16:41 Iterator
-rwxrwxr-x. 1 php-fpm php-fpm  3378 Dec 13 16:41 Iterator.php
-rwxrwxr-x. 1 php-fpm php-fpm  1758 Dec 13 16:41 Section.php
-rwxrwxr-x. 1 php-fpm php-fpm   397 Dec 13 16:41 Tab.php
`

Maybe I have installed a version that is not compatible with Magento 2 version?

**Comment by valugi** [comment]
Hi @deninchoo, 
you were correct I was missing a "<use_separate_process>1</use_separate_process>" in a cron_groups.xml. The only relation with Fastly was that cron task are on the same admin page in Magento.

Thanks for the support
