### ISSUE TITLE
'Fastly' tab in the backend dashboard is broken.

### ISSUE THREAD

**Issue by iskliarenko** [fastly/fastly-magento2#239]
Hello Fastly team,

**Summary of issue**
'Fastly' tab in the backend dashboard doesn't work - Ajax request to /admin/fastlyCdn_Vcl/serviceInfo/.../?isAjax=true controller returns 404 response

**Steps to replicate**

1. Install Fastly module (the latest version) on the latest Magento (2.2.7)
2. Configure Fastly settings (fill up credentials, upload VCL etc)
3. Navigate to Magento backend dashboard > 'Fastly' - you should see an error 'A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.' due to failed Ajax request.

**Comment by deninchoo** [comment]
Hi @iskliarenko ,

I can't seem to replicate the error message issue, however, there is a known bug that breaks the Fastly tab when **javascript minification** is enabled in the Magento advanced developer configuration. A fix for that is on the way here https://github.com/fastly/fastly-magento2/pull/238

I will continue trying to replicate and will update you if I find something.
