### ISSUE TITLE
Flush Magento Cache flushes fastly cache

### ISSUE THREAD

**Issue by kalpmehta** [fastly/fastly-magento2#246]
Hi! We are using Fastly on one of the project where it looks like when we flush Magento cache, it also flushes Fastly cache. Ideally, **Flush Magento Cache** should only flush magento cache and **Flush Cache Storage** should flush magento as well as all the other caches like Fastly's cache.

Because of this issue, whenever client flushes magento cache, we see spike in CPU and memory. I would expect Fastly to soft purge the cache at least, so all the requests do not hit the origin server at once.

Thanks

**Comment by vvuksan** [comment]
Fix part of 1.2.84.
