### ISSUE TITLE
Magento 2.3 Support

### ISSUE THREAD

**Issue by brideo** [fastly/fastly-magento2#253]
## Preqs

I am installing Fastly on version 2.3 and I don't believe they are compatible. I have configured the extension and the "Test Connection" button works.

* Magento 2.3
* Fastly Configured 
* API keys entered and test connection successful 

## Expected Result

* Click the "Automatic Upload & Service Activation" button for VCL snippets to be uploaded to Fastly. 

## Actual Result 

* Button does nothing, no network activity, console errors or feedback

## Work Around

For now, I just hardcoded the request parameters in the controller and executed in manually via CLI.

```
<?php

require __DIR__ . '/app/bootstrap.php';

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
$objectManager = $bootstrap->getObjectManager();

/** @var \Magento\Framework\App\State $state */
$state = $objectManager->get(\Magento\Framework\App\State::class);
$state->setAreaCode('frontend');

/** @var \Fastly\Cdn\Controller\Adminhtml\FastlyCdn\Vcl\Upload $upload */
$upload = $objectManager->create(\Fastly\Cdn\Controller\Adminhtml\FastlyCdn\Vcl\Upload::class);
$upload->execute();
```

**Comment by deninchoo** [comment]
Hi @brideo ,

config values such as the Fastly credential values can sometimes get cached, please make sure to save the configuration via the "Save Config" button and clear the cache before attempting to use any of the Fastly functionalities as many of the buttons will not have any event listeners bound to them unless the service gets successfully validated when the Fastly configuration gets loaded (if the credentials are cached as empty, service validation will fail). The test connection success message reminds you to clear the cache, but I will see what we can do to make this more clear in a future update.

Please let me know if this helps with your issue.

**Comment by brideo** [comment]
Hi @deninchoo,

I did flush the cache but still had no luck, I got around the issue with the above snippet.

**Comment by deninchoo** [comment]
Hmm, are there any other Fastly buttons that are completely unresponsive? Also, when you click the "Fastly Configuration" tab that reveals the credential fields, test connection, upload buttons and other subcategories, can you see a GET request in the console log for `<domain>/admin/admin/fastlyCdn_Configuration/serviceInfo/`? Does the response return a true status and info about the Fastly service?

**Comment by wpoortman** [comment]
Guys,

Any update on this matter? I'm trying to configure this in a 2.2.5 instance which doesn't allow me to press any button except from the "Test credentials" button.

**Comment by deninchoo** [comment]
Hi @wpoortman, I was unable to reproduce the issue, could you perhaps look at my comment from above and tell me if you are getting the desired result from the serviceInfo request in the browser console log?

**Comment by wpoortman** [comment]
Hej @deninchoo, I don't unfortunate. The strange thing is that we've installed the module in multiple shops and this is the first time we have this issue. On the other hand, it's strange that someone else bumps into this problem also.

I'm gonna dive some deeper into this matter and hopefully come back with a solution tomorrow.

**Comment by jspoe** [comment]
Hi @deninchoo, @brideo 

I'm a colleague of @wpoortman and debugged this issue a little to figure out what is going on.
The flow to setup Fastly in Magento is as following:
- Enter service ID
- Enter API Token
- Test credentials

When you open the Fastly configuration, a XHR call is being made. However, if your configuration inside Fastly was not configured completely and the configuration is not active yet, you are not able to click any buttons. Problem is, you don't receive any message about an inactive configuration either.

Suggested solution: Add a notification on the completion of the XHR call that the configuration is (still) inactive.

@brideo Is this the same situation you have?

**Comment by sagepath-aboyd** [comment]
Same problem - you have to click 'Save Config' and then go back in to Fastly configuration to get the Upload VCL button to do anything - on Commerce v2.3.2.

Not a blocker but super confusing UX. Probably needs an improvement ticket, though I'm not sure how to create one.
