### ISSUE TITLE
Cachingconfig with Image Optimizer

### ISSUE THREAD

**Issue by nebtag** [fastly/fastly-magento2#273]
Hi,
After installing Faslty plugin on Magento 2, I uploaded then the config as described in the Doc, which then uploaded snippets to my service on Fastly. But there is a problem with a snippet called "magentomodule_fetch" that overrides caching control and set it to PRIVATE. This setting doesn't allow the use of Image Optimization by Fastly because IO need the content (images) to be cached. Although we can change the snippet manually but it is not how the plugin supposed to work. Can you a look at this issue? Thank you.

Snippet code :

    if (beresp.http.Cache-Control ~ "private|no-cache|no-store") {
        set req.http.Fastly-Cachetype = "PRIVATE";
        return (pass);
    }

**Comment by vvuksan** [comment]
This VCL snippet applies to responses received by your origin. It's a safety precaution which doesn't cache any responses that have Cache-Control of private, no-cache or no-store.

I imagine that your images are including a no-cache in their Cache Control. You can either fix that on your backend (preferable) or add a snippet on Fastly that resets those headers for things like images.

**Comment by nebtag** [comment]
solved after creating a new snippet reseting headers
