### ISSUE TITLE
Compilation Error after 1.2.105 upgrade on Cloud 2.3.1

### ISSUE THREAD

**Issue by opepin** [fastly/fastly-magento2#285]
The deployment log reads : 

Fastly\Cdn\Model\View\Asset\Image
          		Incompatible argument type: Required type: string. Actual type: \Fastly\Cdn\Model\View\Asset\filePath; File:
           /app/vendor/fastly/magento2/Model/View/Asset/Image.php

Full log sequence 

nterception cache generation... 6/7 [===========>-]  85% 5 mins 440.0 MiBErrors during compilation:
21:22:49           	Fastly\Cdn\Model\View\Asset\Image
21:22:49           		Incompatible argument type: Required type: string. Actual type: \Fastly\Cdn\Model\View\Asset\filePath; File:
21:22:50           /app/vendor/fastly/magento2/Model/View/Asset/Image.php
21:22:50           
21:22:50           Total Errors Count: 1
21:22:50           
21:22:50           In Log.php line 92:
21:22:50                                       
21:22:50             Error during compilation  
21:22:50                                       
21:22:50           
21:22:50           setup:di:compile
21:22:50             
21:22:50         [2019-06-19 01:21:46] CRITICAL: Command php ./bin/magento setup:di:compile  --ansi --no-interaction returned code 1  
21:22:50         W: 
21:22:50         W: In CompileDi.php line 63:
21:22:50         W:                                                                                
21:22:50         W:   Command php ./bin/magento setup:di:compile  --ansi --no-interaction returne  
21:22:50         W:   d code 1                                                                     
21:22:50         W:                                                                                
21:22:50         W: 
21:22:50         W: In Shell.php line 110:
21:22:50         W:                                                                                
21:22:50         W:   Command php ./bin/magento setup:di:compile  --ansi --no-interaction returne  
21:22:50         W:   d code 1                                                                     
21:22:50         W:                                                                                
21:22:50         W: 
21:22:50         W: build:generate
21:22:50         W: 
21:22:50       
21:23:03       E: Error building project: The build hook failed with status code 1. Aborted build.
21:23:05 
21:23:05     E: Error: Unable to build application, aborting.
21:23:05 
21:23:05

**Comment by uabassguy** [comment]
I have created a PR which resolves this error. Maintainers please merge at your earliest convenience.

https://github.com/fastly/fastly-magento2/pull/286

**Comment by uabassguy** [comment]
@deninchoo see above

**Comment by vvuksan** [comment]
Fix released in 1.2.106
