### ISSUE TITLE
Resizing issues with "Enable Deep Image Optimization" on product list page

### ISSUE THREAD

**Issue by sdesmet** [fastly/fastly-magento2#287]
Hi,

We seeing this issue on our client's [website](https://www.nahdionline.com/en/ ) when we set "Enable Deep Image Optimization" to Yes.

![image](https://user-images.githubusercontent.com/750318/59771524-c8eee480-92a1-11e9-9339-aff73e7b3da8.png)

The issue does not happen when we use native Magento image resizing.

![image](https://user-images.githubusercontent.com/750318/59773216-2a648280-92a5-11e9-8b90-24ef6a63bef1.png)

Running on 1.2.104.

Thanks

**Comment by deninchoo** [comment]
Hi @sdesmet, I will look into it ASAP

**Comment by sdesmet** [comment]
Hi guys,

Thanks for looking into this. We can look into upgrading, but wondering if it's actually going to solve the issue?

I'm getting the same problem when I disable Canvas in system config:

![image](https://user-images.githubusercontent.com/750318/59776765-4408c880-92ab-11e9-8d41-ff692928732f.png)

Thanks

**Comment by vvuksan** [comment]
I believe the bug is in the fact canvas is not getting set so toggling it back and forth in the UI doesn't do anything. This should have been resolved in 1.2.105.

**Comment by sdesmet** [comment]
Okay, I'll upgrade and check the result and revert back. Thanks.

**Comment by sdesmet** [comment]
I've deployed the upgrade to our staging environment and the issue persist. curl'ing the origin server, getting this in the response headers:

`Fastly-Module-Enabled: 1.2.106`

so sure the module has been updated.

**Comment by sdesmet** [comment]
Might be interesting, seeing the following ("Failed to shrink image") when contacting origin server directly for some of the images that aren't rendering properly. 

```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 88906
Cache-Control: max-age=31536000
Content-Type: image/jpeg
Etag: "w8/lTqEjiFMcyZAu30QaiiUEQO36SavKmfCCsPBPSoQ"
Expires: Thu, 18 Jun 2020 15:57:29 GMT
Fastly-Io-Info: ifsz=88906 idim=568x1500 ifmt=jpeg ofsz=88906 odim=568x1500 ofmt=jpeg
Fastly-Io-Warning: Failed to shrink image
Fastly-Stats: io=1
X-Debug-Info: eyJyZXRyaWVzIjowfQ==
X-Platform-Server: i-0086ebedf39553142
X-Request-Id: 3oq52tmpvgfbiqvde6vl2gt3
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
Date: Wed, 19 Jun 2019 16:10:39 GMT
Age: 790
X-Served-By: cache-sin18048-SIN, cache-lhr6350-LHR
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
strict-transport-security: max-age=31536000
Vary: Accept
```

**Comment by vvuksan** [comment]
Is that canvas setting on or off now ? It should generally be on.

**Comment by vvuksan** [comment]
Failed to shrink image is a red-herring unfortunately. The canvas query argument is missing. For example if I edit the HTML in the inspector and add &canvas=262:262 I get the proper look

![image](https://user-images.githubusercontent.com/260877/59784010-73114100-928f-11e9-937b-4608c8838cb4.png)

**Comment by sdesmet** [comment]
Indeed, that was the issue. Thanks.
