### ISSUE TITLE
Last released version of fastly extension isn't compatible with php 7.3

### ISSUE THREAD

**Issue by andriyShevtsov** [fastly/fastly-magento2#298]
Magento 2.3.3. which is not released yet supports php.7.3 but fastly-magento2 version 1.2.112 doesnt support it.

**Comment by YPyltiai** [comment]
@vvuksan , may you guys fix this please, since 2.3.3 is coming very soon?

**Comment by andriyShevtsov** [comment]
It's important fix for us. Please provide some updates

**Comment by deninchoo** [comment]
Hi @andriyShevtsov, I will look into this, however, the compatibility update might not be merged/released until sometime next week as @vvuksan might be unavailable. If you need the update before then, I'm sure I can deliver the update to you in some other way.

**Comment by vvuksan** [comment]
Can you elaborate on the issues you are observing?

**Comment by andriyShevtsov** [comment]
Let me check. The cause probably in composer.json
```
    "require": {
        "php": "~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0",
```

**Comment by andriyShevtsov** [comment]
![production_stretch](https://user-images.githubusercontent.com/25657845/63455555-9f257b80-c412-11e9-8445-2168243db9bf.jpg)

**Comment by vvuksan** [comment]
It looks like it's just a composer adjustment.

**Comment by andriyShevtsov** [comment]
I suppose you are right

**Comment by vvuksan** [comment]
I made the change in 1.2.113 and tagged the release. Please give it a try.

**Comment by andriyShevtsov** [comment]
Thank you. It works
