### ISSUE TITLE
The message 'Plugin VCL version is outdated! Please re-Upload.' constantly displayed even after a successful VCL uploading.

### ISSUE THREAD

**Issue by iskliarenko** [fastly/fastly-magento2#323]
The message _'Plugin VCL version is outdated! Please re-Upload.'_ constantly displayed even after a successful VCL uploading.

**STEPS TO REPLICATE:**
1) Install the latest version of Magento with the latest Fastly_CDN.
2) Configure and upload VCL via Stores > Configuration > Advanced > System> Full Page Cache > Fastly Configuration.
3) You can see a warning  'Plugin VCL version is outdated! Please re-Upload.' under 'Upload VCL to Fastly' button.
4) Click on 'Upload VCL to Fastly'.
5) Popup will open. Click on the 'Upload' button.
6) Click 'Save Config' button or refresh the page.
7)  You still can see a warning  _'Plugin VCL version is outdated! Please re-Upload.'_ 

**EXPECTED RESULTS:**
VCL should upload successfully and warning should disappear.
**ACTUAL RESULTS:**
_"Plugin VCL version is outdated! Please re-Upload."_ message.

**Comment by vvuksan** [comment]
We will look into it.

**Comment by vvuksan** [comment]
Fixed in #327. Will be part of release 1.2.123.
