### ISSUE TITLE
Add the ability to preview VCL to be uploaded before uploading

### ISSUE THREAD

**Issue by mpchadwick** [fastly/fastly-magento2#324]
Uploading the new VCL can be scary (especially if an emergency change needs to be made and it's not happening during a normal maintenance window). It would be nice if the module could show you the VCL it _would_ upload prior to actually uploading it. Then, you could use the versions interface to get the current version VCL and diff them to see any changes. The biggest worry is that for one reason or another a change was made directly in the Fastly UI that would be overwritten when uploading via the Magento admin.

**Comment by vvuksan** [comment]
This is already possible. You can upload VCL without activating it then going to Tools > List versions and viewing generated VCL before activating.
