### ISSUE TITLE
Slow I/O calls on Magento frontend

### ISSUE THREAD

**Issue by IvanChepurnyi** [fastly/fastly-magento2#329]
When extension generates image URLs it uses `getimagesize` and `file_exists` for an edge when the original image is smaller than a requested image to resize (merchant usually do the opposite - upload huge images). `getimagesize` is an incredibly expensive file call that takes a lot of time on large files like product pictures, it is even worse when you have scalable environment where product images are stored on shared file system mount (NFS, GlusterFS). 

There are two options to fix an issue:
- A quick fix by just patching the module via composer patches if you don't serve smaller then original images and you don't have missing image files (majority of merchants):
```
Index: Model/Product/Image.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Model/Product/Image.php	(date 1574701007174)
+++ Model/Product/Image.php	(date 1574701007174)
@@ -182,17 +182,6 @@
 
     private function adjustSize()
     {
-        $originalImage = $this->_mediaDirectory->getAbsolutePath($this->getBaseFile());
-        $originalSize = getimagesize($originalImage);
-
-        if ($this->getWidth() > $originalSize[0]) {
-            $this->setWidth($originalSize[0]);
-        }
-
-        if ($this->getHeight() > $originalSize[1]) {
-            $this->setHeight($originalSize[1]);
-        }
-
         $this->fastlyParameters['width'] = $this->_width;
         $this->fastlyParameters['height'] = $this->_height;
```
- A complete fix for the case when you might serve such images:
   - Create indexer that stores image sizes from media gallery into separate table
   - Create service model that loads sizes from database on product and its collection after load events and populates in memory information about images from those models.
   - Replace image size retrieval for product with service model that that service model
   - In case if image does not exists in preloaded data of service model use placeholder for image source instead of file_exists call.

**Comment by vvuksan** [comment]
We'll remove these calls as defaults and allow users with edge cases to turn these calls on.
