### ISSUE TITLE
Allow Website/Store level Custom Synthetic Pages

### ISSUE THREAD

**Issue by atishgoswami** [fastly/fastly-magento2#331]
Error pages or Maintenance pages can have design alteration depending on the website/store theme that can be getting used for the project.

As of now the settings to add custom error / maintenance page HTML is provided at the global config level, which is not helpful if we are have multiple websites with different themes and layout designs

Is there any workaround available for this ?

**Comment by vvuksan** [comment]
I realized I never answered this query.

To solve this you would need to define multiple Response Objects (https://docs.fastly.com/en/guides/creating-error-pages-with-custom-responses) with the HTML contents you want. 

Only gotcha is that you have to make sure you add a condition with 

   req.http.ResponseObject == "970" 

and it needs to have a higher priority than the default one. **Priority of less than 9** should do it. So if you wanted to do it for a specific domain you would do a condition like this

   req.http.ResponseObject == "970"  && req.http.host == "www.domain1.com"
