### ISSUE TITLE
Visible page re-rending (page reload) when using GeoIP automatic redirect

### ISSUE THREAD

**Issue by nige-one** [fastly/fastly-magento2#346]
While the GeoIP functionality works as expected, we see a visible re-rendering of the page on the first page visit.
Since the redirect is done by a `document.location.href` via the uiComponent
https://github.com/fastly/fastly-magento2/blob/1c1033dbfeb1eb33bbf553a6f6eb830963789d42/view/frontend/web/js/redirect.js#L10
it is depending on Magento's require.js frontend-stack, which is too slow to take place before the default store rendering.
The effect is that the default store is beginning to render and then the redirect causes a new rendering of the 'correct' store view which the client should be redirected to.
This is tested in 2.3.3 on the Magento Cloud but I'm sure the Magento version doesn't effect this intended behaviour.
Maybe this could be replaced by a direct DOM rendered JS to follow the DOM JS execution order instead of using the slow Magento frontend JS stack?

**Comment by vvuksan** [comment]
We'll investigate this.

**Comment by nige-one** [comment]
@vvuksan is there any update?

**Comment by vvuksan** [comment]
Hi Nicolas,

It's on the list of things to do. Unfortunately I do not have a time update when it's going to be done.

**Comment by nige-one** [comment]
@vvuksan I've tested https://github.com/fastly/fastly-magento2/pull/360 and it looks very promising. Still some tests to go.

**Comment by nige-one** [comment]
@vvuksan although is sufficient in terms of the rendering/impression, browsers still load a bunch of assets from the "first" hit, before the 302 resolves to the new page code 200 and alot of files are fetched again. Regarding cached images this is not so huge - but assets from different paths (think of Magento's language codes inside the pub/static dir) cause unneeded heavy traffic.
I think this has to be resolved on your servers instead of the user's client. Just my 2 cents...

**Comment by vvuksan** [comment]
This is a good point and we are aware of this however it makes the implementation very complex and potentially brittle. The current solution is the most flexible implementation as it allows Magento users to customize the look and feel of the redirect dialog e.g. allowing user to opt out of redirect etc. It's by no means perfect and I realize there are dozen other ways of implementing this and we have over time seen as many different implementations that all had their own edge cases. There hasn't been a consistent set of asks from end users and with potential risk surface around redirect (e.g. infinite loops) I am hesitant to make any major changes to current functionality.
