### ISSUE TITLE
Unable to add vary based on user-agent

### ISSUE THREAD

**Issue by toshanrdb** [fastly/fastly-magento2#347]
Hello,

We want to add vary on fastly so as when a bot hits the website it is cache differently from that of a normal user.
The a call from a bot user-agent is somehow cached same as a normal user
Find below the vcl snippets from magento:
vcl_recv: 
if ( req.http.User-Agent ~ "(?i)(ads|Google|bing|msn|yandex|baidu|ro|career|seznam|)bot" ) 
{
 set req.http.X-UA-Device = "Googlebot";
 set req.http.Vary = " X-UA-Device";
   } 
else {
set req.http.X-UA-Device = "Desktop";
}
vcl_fetch:
if ( beresp.http.Vary ) {
   set beresp.http.Vary = "Accept-Encoding, X-UA-Device";
}

**Comment by vvuksan** [comment]
That is pretty bizarre. That should work. 

We do have an Edge Module that does something very similar for mobile devices and has the addition for bots

https://github.com/fastly/fastly-magento2/blob/master/Documentation/Guides/Edge-Modules/EDGE-MODULE-MOBILE-THEME-SUPPORT.md

I would also recommend you only vary on e.g. HTML. Doing it for all content would result in unnecessary caching of static assets as well.

**Comment by toshanrdb** [comment]
Hi @vvuksan,
Our product static contents are served by an external service. we would like product content for bots to be served from magento instead of the external service.

**Comment by vvuksan** [comment]
I am not sure I understand.

**Comment by vvuksan** [comment]
Can you expand on what the issue is. I am not really understanding what the issue is.
