### ISSUE TITLE
VCL Update returns an error code with magento 2.2.2

### ISSUE THREAD

**Issue by berliozd** [fastly/fastly-magento2#355]
**Steps to Replicate**
- magento version : 2.2.2
- fastly module version : 1.2.129 (setup verison 1.0.13)  

Log in into the backoffice and try to upload the VCL to fastly.
The following url is called : 
/admin/admin/fastlyCdn_Vcl/upload/?isAjax=true

**Actual Result**
A 500 http error code is returned.

**Expected Result**
A 200 http code is returned.

**Findings**
Looking at the nginx log we could see this : 
2020/04/01 17:20:48 [error] 1295#1295: *432 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Magento\Config\Model\ResourceModel\Config::saveConfig(), 2 passed in /var/www/magento/vendor/fastly/magento2/Controller/Adminhtml/FastlyCdn/Vcl/Upload.php on line 218 and exactly 4 expected in /var/www/magento/vendor/magento/module-config/Model/ResourceModel/Config.php:37

It says that we call a method saveConfig on object Magento\Config\Model\ResourceModel\Config with the bad number of arguments.

Looking at the magento 2.2.2 code i can see the saveConfig method signature in vendor/magento/module-config/Model/ResourceModel/Config.php : 
`public function saveConfig($path, $value, $scope, $scopeId)`
It really expect 4 arguments.

In a newer version of magento  (2.2.11), i can see the signature has changed for : 
`public function saveConfig($path, $value, $scope = ScopeConfigInterface::SCOPE_TYPE_DEFAULT, $scopeId = 0)`
The 2 last arguments are now optionnal.

It looks like the fastly module is not compatible with some magento version (2.2.2)  in which the code was really expecting 4 arguments.

**Comment by vvuksan** [comment]
I have added this to our ticket backlog.

**Comment by vvuksan** [comment]
Fixed with #358 and will be part of 1.2.130 release.
