### ISSUE TITLE
Fastly not working.

### ISSUE THREAD

**Issue by ethelserth** [fastly/fastly-magento2#357]
Hello all

We installed and configured the extention plus the fastly options. In stat page, on fastly website, no requests are shown, and when sometimes they are, they are all pass. 

Note that our server have also varnish, plus we use ssl. 

Any advice?

**Comment by vvuksan** [comment]
Hi @ethelserth 

We will need more details on what the issue is. Can you open up a ticket with our support with full details e.g. URLs affected, what version of Magento etc.
