### ISSUE TITLE
Magento Admin panel button issue

### ISSUE THREAD

**Issue by hryksbt** [fastly/fastly-magento2#364]
I cannot push any Fastly module setting buttons.
There are buttons such as "Upload VCL to Fastly" or "Enable/Disable". But it doesn't work.
Only "Test credentials" button seems working fine. Test result seems fine and I already purge cache. 
So I cannot complete installation Fastly for my site because of I cannot upload initial VCL snippets. 
I'm using Magento 2.3.4 OSS and latest Fastly_Cdn module.
Can you resolve?

Thank you.

**Comment by qdingx** [comment]
I got the same issue. Do you know any solutions to this?

**Comment by vvuksan** [comment]
Can you check in the Developer Console for any errors ? Also what version of the plugin are you running ?

**Comment by vvuksan** [comment]
Can you update to the latest version (1.2.133) and see if the issue presents itself.

**Comment by hryksbt** [comment]
I updated from 1.2.132 to 1.2.133. But this is not resolved.

**Comment by hryksbt** [comment]
When I open fastly setting menu in admin panel, there is below message in system.log or debug.log.

`[2020-04-29 13:48:14] main.CRITICAL: Return status 404 {"method":"GET","url":"http://example.com/admin/admin/system_config/edit/section/system/key/*******/","invalidateInfo":"https://api.fastly.com/service/******/version//acl"} []`

I masked key information.

Thank you.

**Comment by vvuksan** [comment]
Did you test the credentials to verify they are correct ?

**Comment by hryksbt** [comment]
Yes. Credential test was passed too.

**Comment by hryksbt** [comment]
Hello, this is past more than 1 month. When will you resolve?

**Comment by vvuksan** [comment]
Hi @hryksbt 

Unfortunately I do not have many clues why this is not working for you. It's certainly not something we typically see. Can you check whether all the assets like require.js are being loaded.

**Comment by GrassH** [comment]
Hi @vvuksan,

I debugged the code of the fastly-magento2 module, and I found that [Fastly\Cdn\Helper\Vcl::getCurrentVersion](https://github.com/fastly/fastly-magento2/blob/d688278b9f054e10816900e8d622ab4db1191ed8/Helper/Vcl.php#L61) method could not correctly process the data returned by the Fastly API, causing an error to be thrown. As a result, the “Upload VCL to Fastly” button cannot be used.

Please see https://developer.fastly.com/reference/api/services/service/#list-services.

Thanks

**Comment by vvuksan** [comment]
Thanks for debugging this. We'll add this to be fixed.

**Comment by vvuksan** [comment]
Fixed in #388. Will be part of 1.2.141+
