### ISSUE TITLE
Read Maintenance IP for verifyBot method takes too long

### ISSUE THREAD

**Issue by sivasdescalzo** [fastly/fastly-magento2#399]
Could you please store maintenance IPs in cache?
Imagina having thousands of request per minute, and on every request, PHP needs to read a file in filesystem...

`private function readMaintenanceIp($ip)
    {
        $flagDir = $this->filesystem->getDirectoryWrite(DirectoryList::VAR_DIR);

        if ($flagDir->isExist('.maintenance.ip')) {
            $temp = $flagDir->readFile('.maintenance.ip');
            $tempList = explode(',', trim($temp));
            foreach ($tempList as $key => $value) {
                if (!empty($value) && trim($value) == $ip) {
                    return true;
                }
            }
        }
        return false;
    }`

<img width="1161" alt="Screenshot 2020-08-12 at 09 02 27" src="https://user-images.githubusercontent.com/51407732/89985158-e687c600-dc7a-11ea-9f27-391881d953bc.png">

**Comment by vvuksan-fastly** [comment]
Released as part of 1.2.145
