### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by colinspace48** [fastly/fastly-magento2#4]
Installation -> Magento Module -> Point 4

composer config respositories.fastly-magento2 git "https://[your-github-username]:[your-github-passwd]@github.com/fastly/fastly-magento2.git"

should be:

composer config repositories.fastly-magento2 git "https://[your-github-username]:[your-github-passwd]@github.com/fastly/fastly-magento2.git"

**Comment by phoenix-bjoern** [comment]
@colinspace48 thanks for the hint. fixed.
