### ISSUE TITLE
"Trying to access array offset on value of type int" error occurs when enabling the "Rate limiting" functionality

### ISSUE THREAD

**Issue by pkodithuwakku** [fastly/fastly-magento2#431]
When Magento is installed on PHP 7.4, below mentioned error occurs when trying to enable the "Rate limiting" functionality in Fastly.

`Trying to access array offset on value of type int in vendor/fastly/magento2/Controller/Adminhtml/FastlyCdn/RateLimiting/ToggleRateLimiting.php on line 143`

The Fastly\Cdn\Helper\Vcl::getCurrentVersion method returns an integer, which is the current VCL version number, however https://github.com/fastly/fastly-magento2/blob/master/Controller/Adminhtml/FastlyCdn/RateLimiting/ToggleRateLimiting.php#L143 this code tries to access an array key. Because of that above mentioned error occurs.

**Comment by vvuksan** [comment]
Fix merged.
