### ISSUE TITLE
Impossible to add domains with wildcard

### ISSUE THREAD

**Issue by dhorytskyi** [fastly/fastly-magento2#445]
Impossible to add domains with wildcard. According to documentation wildcard domains are supported.
https://docs.fastly.com/en/guides/working-with-domains#creating-a-domain

**Steps to replicate:**
1. Log in backend Magento
2. Go to Stores -> Configuration -> Advanced -> System
3. In Fastly Configuration -> Domains section
4. Go to Manage Domains
5. Try to add one domain: *.example.com
6. Click Activate

**Expected results:**
Changes should save correctly

**Actual results:**
Error shown: Invalid domain name "*.example.com"

**Comment by smaeda-ks** [comment]
Resolved in #446, Thanks
