### ISSUE TITLE
Serve Adaptive Pixel Ratios for product gallery images

### ISSUE THREAD

**Issue by Leland** [fastly/fastly-magento2#448]
Hi there! As far as I can tell, Adaptive Pixel Ratio only changes the pixel density for product lists - categories, search results, related product lists, and so on. Perhaps the _most_ important area where pixel density plays a role would be PDP image galleries, however: they're a very large image, so images served below a display's target pixel density becomes very noticeable.

Any chance of extending this feature to product galleries as well?

**Comment by vvuksan** [comment]
We'll look into it.

**Comment by Lukas713** [comment]
HI @leklund , [here](https://github.com/fastly/fastly-magento2/pull/452/files) are the  changes that will serve image inside PDP gallery based on window device pixel ratio.

**Comment by Leland** [comment]
Implemented in #452
