### ISSUE TITLE
Feature Request - Extensibility problem in GeoIP

### ISSUE THREAD

**Issue by Dren7755** [fastly/fastly-magento2#450]
We have GetAction controller which is responsible for getting customer country_code and redirecting him to needed url.
The problem happens when we want to extend this controller to use another source for country_code (like customer session or etc.)
This source is hardcoded here https://github.com/fastly/fastly-magento2/blob/master/Controller/GeoIP/GetAction.php#L133
So to change source we need to rewrite whole controller class.

Please create some extensible point for that. I guess some CountryCodeProviderInterface can be good idea.

**Comment by dpotkoc** [comment]
@Dren7755 I prepared code improvement for this request, but please could you tell me why you want to override **country_code** parameter?


Thanks in advance
Domagoj

**Comment by vladyslav-sikailo-decima** [comment]
There can be a lot of cases, like:
- Customer want to select prefered country in my account
- redirect to country from cookie (which was selected on frontend)
- etc
