### ISSUE TITLE
Add custom header for maintenance mode 503 response

### ISSUE THREAD

**Issue by tristanblattmansh** [fastly/fastly-magento2#468]
When monitoring for uptime, there are typically 2 situations that return 503. 
Either the origin is unavailable or the site is in maintenance mode.
When enabling maintenance mode through the Magento Cloud CLI, `php bin/magento maintenance:enable` it creates a file `var/.maintenance.flag` which can be used by some monitoring tools.

When enabling maintenance mode via the Magento CLI for Fastly, `php bin/magento fastly:maintenance -e` (or via the UI) there is no flag file created. 

Adding a custom header response would enable http monitoring to detect maintenance mode and prevent false positives for outage monitoring.
(or, create the file `var/.maintenance.flag` on enable and delete on disable)

**Comment by tristanblattmansh** [comment]
Or alternatively - include a `status` option in in the CLI
eg. `php bin/magento fastly:maintenance -s`
Which returns the whether maintenance mode is enabled or disabled.

**Comment by smaeda-ks** [comment]
@tristanblattmansh 

The easiest way is:

```diff
diff --git a/etc/vcl_snippets/deliver.vcl b/etc/vcl_snippets/deliver.vcl
index 3809bd3..455a0d0 100644
--- a/etc/vcl_snippets/deliver.vcl
+++ b/etc/vcl_snippets/deliver.vcl
@@ -40,6 +40,9 @@
     # Add an easy way to see whether custom Fastly VCL has been uploaded
     if ( req.http.Fastly-Debug ) {
         set resp.http.Fastly-Magento-VCL-Uploaded = "1.2.165";
+        if (table.lookup(magentomodule_config, "allow_super_users_during_maint", "0") == "1") {
+            set resp.http.Fastly-Magento-Maintenance-Mode = "on";
+        }
     } else {
         remove resp.http.Fastly-Module-Enabled;
         remove resp.http.fastly-page-cacheable;
```

so when Fastly Magento maintenance mode is set, `Fastly-Magento-Maintenance-Mode` response header is added, but only if you send a request with `Fastly-Debug` request header added. Does that work? If so, I'll make this change in the next version. Thanks

**Comment by tristanblattmansh** [comment]
@smaeda-ks just following up on this, The solution you proposed would be perfect for us, if you're able to add it in
