### ISSUE TITLE
Cannot read property 'jsonConfig' of undefined in swatch-renderer-mixin.js:11 

### ISSUE THREAD

**Issue by sandeep570** [fastly/fastly-magento2#475]
Hello Team,
After upgrading the fastly module version to 1.2.163 we are getting the below error 
Error: Cannot read property 'jsonConfig' of undefined in swatch-renderer-mixin.js:11 
Anyone, please help me of resolving the error or guide me on how to resolve this because this is a blocker for us.
![Screenshot from 2021-08-19 00-19-03](https://user-images.githubusercontent.com/45820900/129955460-9e88c73e-8394-4fe9-93e6-e6c527da30cc.png)

Thanks in advance

**Comment by dpotkoc** [comment]
Hello @sandeep570 you have old and wrong version of file: [app/code/Fastly/Cdn/view/frontend/web/js/swatch-renderer-mixin.js](https://github.com/fastly/fastly-magento2/blob/master/view/frontend/web/js/swatch-renderer-mixin.js)

Please check our current version and fix you enviroment.

Regards,
Domagoj
