### ISSUE TITLE
GetUpdateFlag call flushes all configuration

### ISSUE THREAD

**Issue by eristyl** [fastly/fastly-magento2#499]
Hello,

When the ajax call checkUpdateFlag is made, it triggers $this->typeList->cleanType('config'); which ends in a flush of all Redis config cache keys.

Which means that displaying the Fastly configuration is Magento admin flushes all config cache.
There are the "redis-cli monitor | grep DEL" logs related to this ajax call:

`1642063406.667723 [0 127.0.0.1:xxxx] "DEL" "zc:k:6s5d4fs54_MEDIA_GALLERY_PATTERNS_CACHEID" "zc:k:6s5d4fs54_GLOBAL__CONFIG_CACHE" "zc:k:6s5d4fs54_PROVIDER_ACL_RESOURCES_CACHE" "zc:k:6s5d4fs54_CONSTRAINT_CONFIG_CACHE" "zc:k:6s5d4fs54_COMMUNICATION_CONFIG_CACHE" "zc:k:6s5d4fs54_INDICES_CONFIG_OPTIMIZER" "zc:k:6s5d4fs54_APP_35C0BF370AE35F8C482DC31B8A81FC2F" "zc:k:6s5d4fs54_CONNECTION_CONFIG_CACHE" "zc:k:6s5d4fs54_SYSTEM_SCOPES" "zc:k:6s5d4fs54_SYSTEM_WEBSITES_BASE" "zc:k:6s5d4fs54_ELASTICSUITE_REQUEST_DECLARATION" "zc:k:6s5d4fs54_GLOBAL__EVENT_CONFIG_CACHE" "zc:k:6s5d4fs54_ADMINHTML__RESOURCESCACHE" "zc:k:6s5d4fs54_ANALYSIS_CONFIG" "zc:k:6s5d4fs54_AUTHORIZATION_RULE_CACHED_DATA" "zc:k:6s5d4fs54_PAYMENT_CONFIG" "zc:k:6s5d4fs54_FRONTEND__CSP_WHITELIST_CONFIG" "zc:k:6s5d4fs54_SYSTEM_WEBSITES_ADMIN" "zc:k:6s5d4fs54_INDICES_CONFIG" "zc:k:6s5d4fs54_APP_108B5EBA5ECACA9F6E9F88D4CD04D6E0" "zc:k:6s5d4fs54_CRON_GROUPS_CONFIG_CACHE" "zc:k:6s5d4fs54_SYSTEM_STORES_0" "zc:k:6s5d4fs54_CRONTAB__RESOURCESCACHE" "zc:k:6s5d4fs54_BACKEND_MENU_OBJECT" "zc:k:6s5d4fs54_SMILE_ELASTICSUITE_INITIAL_CONFIG" "zc:k:6s5d4fs54_MESSAGE_QUEUE_CONSUMER_CONFIG_CACHE" "zc:k:6s5d4fs54_RESOLVED_STORES_D1BEFA03C79CA0B84ECC488DEA96BC68" "zc:k:6s5d4fs54_GLOBAL__CSP_WHITELIST_CONFIG" "zc:k:6s5d4fs54_ADDRESS_FORMAT" "zc:k:6s5d4fs54_SYSTEM_STORES_1" "zc:k:6s5d4fs54_SYSTEM_DEFAULT" "zc:k:6s5d4fs54_MAGENTO_ANALYTICS_REPORTXML_CACHEID" "zc:k:6s5d4fs54_MAGE_VERSION" "zc:k:6s5d4fs54_ADMINHTML__EVENT_CONFIG_CACHE" "zc:k:6s5d4fs54_EAV_ATTRIBUTES" "zc:k:6s5d4fs54_FRONTEND__EVENT_CONFIG_CACHE" "zc:k:6s5d4fs54_SYSTEM_WEBSITES_0" "zc:k:6s5d4fs54_SMILE_RECONFIGURE_CONFIG" "zc:k:6s5d4fs54_INDICES_CONFIG_TRACKING_LOG_EVENT" "zc:k:6s5d4fs54_LOGGING_CONFIG" "zc:k:6s5d4fs54_EMAIL_TEMPLATES" "zc:k:6s5d4fs54_RESOLVED_STORES_D7A094A061F9E5121D10DBCA79ABB6E0" "zc:k:6s5d4fs54_SYSTEM_STORES_BOBRICO" "zc:k:6s5d4fs54_PAGE_TYPES_CONFIG" "zc:k:6s5d4fs54_UI_COMPONENT_CONFIGURATION_DATA_NOTIFICATION_AREA" "zc:k:6s5d4fs54_MVIEW_CONFIG" "zc:k:6s5d4fs54_ADMINHTML__BACKEND_SYSTEM_CONFIGURATION_STRUCTURE" "zc:k:6s5d4fs54_INDICES_CONFIG_TRACKING_LOG_SESSION" "zc:k:6s5d4fs54_AUTHORIZATION_ROLE_CACHED_DATA" "zc:k:6s5d4fs54_INDICES_CONFIG_CATALOG_CATEGORY" "zc:k:6s5d4fs54_MAGENTO_ANALYTICS_CACHEID" "zc:k:6s5d4fs54_SYSTEM_STORES_2" "zc:k:6s5d4fs54_FRONTEND__ROUTESCONFIG" "zc:k:6s5d4fs54_SYSTEM_STORES_ADMIN" "zc:k:6s5d4fs54_SMILE_PUBSUB" "zc:k:6s5d4fs54_INDEXER_CONFIG" "zc:k:6s5d4fs54_EXTENSION_ATTRIBUTES_CONFIG" "zc:k:6s5d4fs54_SECTIONS_INVALIDATION_CONFIG" "zc:k:6s5d4fs54_INITIAL_CONFIG" "zc:k:6s5d4fs54_PRODUCT_TYPES_CONFIG" "zc:k:6s5d4fs54_DB_IS_UP_TO_DATE" "zc:k:6s5d4fs54_PRODUCT_OPTIONS_CONFIG" "zc:k:6s5d4fs54_MEDIA_CONTENT_PATTERNS_CACHEID" "zc:k:6s5d4fs54_INDICES_CONFIG_CATALOG_PRODUCT"  "zc:k:6s5d4fs54_APP_14D56884DCC568789CA1733D23CB4BF4" "zc:k:6s5d4fs54_CRONTAB_CONFIG_CACHE" "zc:k:6s5d4fs54_SYSTEM_WEBSITES_1" "zc:k:6s5d4fs54_MESSAGE_QUEUE_CONFIG_CACHE" "zc:k:6s5d4fs54_FRONTEND__RESOURCESCACHE" "zc:k:6s5d4fs54_CRONTAB__EVENT_CONFIG_CACHE" "zc:k:6s5d4fs54_SYSTEM" "zc:k:6s5d4fs54_APP_CE79F7EF764E9F981C8549B9DBEC468F" "zc:k:6s5d4fs54_ADMINHTML__ROUTESCONFIG" "zc:k:6s5d4fs54_UI_COMPONENT_CONFIGURATION_DEFINITION_DATA" "zc:k:6s5d4fs54_APP_4169C5DEEEB8F84FEFBFAC574BE2769B" "zc:k:6s5d4fs54_UI_COMPONENT_TEMPLATES" "zc:k:6s5d4fs54_ADMINHTML__CSP_WHITELIST_CONFIG" "zc:k:6s5d4fs54_ADMINHTML__CONFIG_CACHE" "zc:k:6s5d4fs54_GLOBAL__RESOURCESCACHE"`

**Comment by dpotkoc** [comment]
@eristyl Please could you send to us exactly Magento version.

Thnx
Domagoj

**Comment by eristyl** [comment]
Hello @dpotkoc,

I'm using: Magento ver. **2.4.2-p1**

Regards

**Comment by vvuksan** [comment]
Fixed in 1.2.178
