### ISSUE TITLE
Blank page on cache page in magento 2.0.7 admin

### ISSUE THREAD

**Issue by Galillei** [fastly/fastly-magento2#5]
I try use your module, but catch blank page on admin. Also when i try do compilation i catch error in fastly module. I try fixed this issues this https://github.com/Galillei/fastly-magento2

**Comment by ryannguyen** [comment]
This is happening to me too.  Here's the trace:

`Notice: Undefined index: class in /var/www/magento/vendor/magento/framework/View/Layout/Generator/Block.php on line 213
#0 /var/www/magento/vendor/magento/framework/View/Layout/Generator/Block.php(213): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/magent...', 213, Array)
#1 /var/www/magento/vendor/magento/framework/View/Layout/Generator/Block.php(124): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'cache.additiona...')
#2 /var/www/magento/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#3 /var/www/magento/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#4 /var/www/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#5 /var/www/magento/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#6 /var/www/magento/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#7 /var/www/magento/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#8 /var/www/magento/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#9 /var/www/magento/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#10 /var/www/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#11 /var/www/magento/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#12 /var/www/magento/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Backend...')
#13 /var/www/magento/vendor/magento/module-backend/Controller/Adminhtml/Cache/Index.php(20): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Backend...')
#14 /var/www/magento/var/generation/Magento/Backend/Controller/Adminhtml/Cache/Index/Interceptor.php(24): Magento\Backend\Controller\Adminhtml\Cache\Index->execute()
#15 /var/www/magento/vendor/magento/framework/App/Action/Action.php(102): Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor->execute()
#16 /var/www/magento/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#19 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor->___callParent('dispatch', Array)
#20 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor), Array, 'adminAuthentica...')
#21 /var/www/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#22 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#24 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor), Array, 'log')
#25 /var/www/magento/vendor/magento/module-logging/App/Action/Plugin/Log.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 [internal function]: Magento\Logging\App\Action\Plugin\Log->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#28 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor), Array, 'designLoader')
#29 /var/www/magento/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#30 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#32 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor), Array, 'adminMassaction...')
#33 /var/www/magento/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#36 /var/www/magento/var/generation/Magento/Backend/Controller/Adminhtml/Cache/Index/Interceptor.php(39): Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /var/www/magento/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Cache\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#40 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#41 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#42 /var/www/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#43 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#44 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#45 /var/www/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#46 /var/www/magento/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#47 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#48 /var/www/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#49 {main}`

**Comment by jondade** [comment]
This should be resolved in 1.0.3 which addressed this issue.
