### ISSUE TITLE
Fastly Rate Limiting not working with Graphql

### ISSUE THREAD

**Issue by Goldfingr9** [fastly/fastly-magento2#504]
The Merchant enabled Fastly Rate Limiting on the environment and set it up for graphql requests but it doesn't appear to be working for the graphql request.
It was set to block after 10 requests in 180 seconds (5 minutes) for the path /graphql and it doesn't get blocked using this url https://mcstaging.toyota.com/graphql?query={category(id:2){children{name,url_path}}}

Several permutations for the regex path were tried but none of these are working either /graphql(.*), ^/graphql , ^/graphql(.*) , (.*)/graphql(.*)

Rate limiting was proven to work on category pages with regex for path = (.)/catalog/category(.) So fastly seems to be set up properly.
https://mcstaging.toyota.com/default/catalog/category/view/s/parts/id/379/

When checking the header responses for that graphql request, cache miss is returned
curl https://mcstaging.toyota.com/graphql -G -d "query={category(id:2){children{name,url_path}}}" -vo /dev/null -H Fastly-Debug:1

< x-cache: MISS
< x-cache-hits: 0

According to the documentation, this should be cached https://devdocs.magento.com/guides/v2.4/graphql/caching.html
Fastly will only cache GET requests that contain a query parameter in the request URL.

If the same is done for the category page, a cache hit is returned

curl https://mcstaging.toyota.com/default/catalog/category/view/s/parts/id/379/ -vo /dev/null -H Fastly-Debug:1

< x-cache: MISS, HIT
< x-cache-hits: 0, 1

With the fastly rate limit logging enabled, these entries are returned when hitting the category page but not the graphql requests
[2022-02-07 16:16:16] report.INFO: First tag hit during a window. Starting the counter for: "fastly_rl_sensitive_path__174.204.5.87 [] []
[2022-02-07 16:16:41] report.INFO: Hit inside enforcement window: "fastly_rl_sensitive_path__174.204.5.87" Count: 5/10 Window length: 25 secs/180 [] []

Note Different graphql requests were tried but returned the same results. (AKA cache misses with nothing reported in the fastly rate limit log.)

Please advise on if the rate-limiting feature works with graphql queries.

**Comment by Supermanzliu** [comment]
Merchant current protected paths setting: https://nimb.ws/1dFLIN
all below values were tested, same result
/graphql(.*), ^/graphql , ^/graphql(.*) , (.*)/graphql(.*)

**Comment by vvuksan** [comment]
We are looking into it.

**Comment by Supermanzliu** [comment]
Hi Team,
Is the fix in place now? can I ask the merchant to go ahead and test it again?
Kind Regards

**Comment by vvuksan** [comment]
This has been fixed in version 1.2.179. Please update the plugin and restest.
