### ISSUE TITLE
CMS pages are not updated in frontend(cache not cleared)

### ISSUE THREAD

**Issue by sreenathnr-tm** [fastly/fastly-magento2#513]
I have a Magento 2.4.2-p1 Enterprise installation with fastly configured environment. After fastly configuration, the CMS page changes are not visible in the frontend. If I add the ?1(for seeing non-cached) to the end of the URL shows the updated page. If I purge the URL at the single purge section in the backend then the page shows the updated changes.

**Comment by dpotkoc** [comment]
Hello @sreenathnr-tm Please check fastly config option and try to set to **Yes**
![Screenshot from 2022-03-02 13-24-57](https://user-images.githubusercontent.com/553247/156361479-6cb7268d-a2f4-49f8-b04c-39f4bbda6d09.png)
