### ISSUE TITLE
Full Page Cache Issue with CDN Fastly

### ISSUE THREAD

**Issue by zahidhussain20** [fastly/fastly-magento2#515]
Hi, since days, I am facing full page cache isseu with CDN Fastly.
When I enable CDN Fasty full page cache than I am not able to save some form data from admin side.
Here is error generating when I enable this:
`Magento\CacheInvalidate\Observer\InvalidateVarnishObserver->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
`
If disble CDN Fastly full page cache than it save form data otherwise generates above menttioned error.

Hope you will soon reply with solution.
Thanks.

**Comment by vvuksan** [comment]
Can you tell me what version of the plugin are you running and what version of Magento ?

**Comment by dpotkoc** [comment]
@zahidhussain20 Please, could you provide us steps: "how to reproduce issue"?

Please, also send us:
- Magento version
- Fastly Plugin version

Thanks
Domagoj

**Comment by zahidhussain20** [comment]
Yes I have a latest version of CDN Fastly and It is not working with Store Locator by aheadWorks extension. otherside it is work fine.

**Comment by zahidhussain20** [comment]
Hi @dpotkoc  it was bug of magento2 latest version in varnish cache and also it is bug in your module yesterday I resolved myself.
Thanks
