### ISSUE TITLE
Error on executing - fastly:format:serializetojson

### ISSUE THREAD

**Issue by novykov** [fastly/fastly-magento2#520]
**STEPS TO REPRODUCE:**

Setup Magento with Fastly module https://github.com/fastly/fastly-magento2
Run - bin/magento fastly:format:serializetojson

**ACTUAL RESULTS:**
Throws below error
`bin/magento fastly:format:serializetojson
PHP Fatal error: Uncaught Error: Call to undefined method Magento\Enterprise\Model\ProductMetadata::unserialize() in vendor/fastly/magento2/Console/Command/SerializeToJson.php:115`

**Comment by dpotkoc** [comment]
@novykov Hello, please could you provide us exactly php / Magento version?

Thnx

**Comment by novykov** [comment]
@dpotkoc tested on 2.4.3-p1 with php 7.4 and on 2.3.5 with php 7.3
The issue is reproducible on both

**Comment by vvuksan** [comment]
Fixed in 1.2.181
