### ISSUE TITLE
Custom VCL snippet to bypass block cache

### ISSUE THREAD

**Issue by sweta-fcmoto** [fastly/fastly-magento2#524]
Hi, i am looking for custom VCL snippet to bypass Fastly cache from certain dynamic magento blocks.

We have dynamic prices being displayed on category and product pages based on user's IP/country. 

Magento version: 2.4.1-p1 (commerce cloud pro)

**Comment by vvuksan** [comment]
The only way to do it is to add VCL code that returns a pass action based on e.g. url

Snippet type: recv

```
if ( req.url.path ~ "^/someurl" ) {
   set req.http.X-Pass = 1;
}
```
