### ISSUE TITLE
don't use last version ! VCL deleted for no reason 

### ISSUE THREAD

**Issue by BeardTech** [fastly/fastly-magento2#540]
In the last version[1.2.182] you have added a vcl remover so when we upload new version it delete image optimisation, WAF, force TLS,..

![image](https://user-images.githubusercontent.com/19796076/173640323-ae0cd54a-a203-4a0d-a31a-9880b96649f3.png)

this code is not tested for sure and remove waf vlc... so i consider it very dangerous...

even if we re-enable image optimization, waf ect it will be removed with a next upload.

**Comment by vvuksan** [comment]
Hi @BeardTech. Thanks for reporting this. It appears you are right. I will go ahead and remove the release :-(.

**Comment by BeardTech** [comment]
you're very fast thank you !
