### ISSUE TITLE
Geo IP only works with stores belong to websites which the request was made from.

### ISSUE THREAD

**Issue by kavingas** [fastly/fastly-magento2#549]
**Steps**
- Create 2 or more websites with store views
- Configure Fastly GeoIP redirect to redirect requests to a different store that belongs to a website other than the request was made from
- Access the store using an IP matching the GeoIP redirect rule

**Actual Result**
The request is not getting redirected

**Expected Result**
The request matching the GeoIP should get redirected to the desired store.

**Extra details**
The code under https://github.com/fastly/fastly-magento2/blob/master/Model/Config.php#L1155 checks whether the target store belongs to the same website that the request was made from.

**Comment by vvuksan** [comment]
We'll look into it. It may take a bit as there is quite a bit of risk involved.

**Comment by vvuksan** [comment]
Released in 1.2.188
