### ISSUE TITLE
maint_allowlist not exempt from rate-limit

### ISSUE THREAD

**Issue by joaooliveirap** [fastly/fastly-magento2#556]
According to your [docs](https://github.com/fastly/fastly-magento2/blob/master/Documentation/Guides/RATE-LIMITING.md)

Following users are exempt from blocking:
IPs defined in var/.maintenance.ip (See Maintenance Mode guide for more details)

var/.maintenance.ip updates acl maint_allowlist but this acl is never used to exempt the ips from getting blocked.
As a result rate limit will return 429 also for IPs that are on the maintenance list.

Open PR #555

**Comment by vvuksan** [comment]
Included in 1.2.186
