### ISSUE TITLE
Maintenance page cant load files from magento (css, images...) returns 503

### ISSUE THREAD

**Issue by marquesdevopen** [fastly/fastly-magento2#568]
The maintenance page is not able to load files (images and css) that are inside pub/error when maintenance is enabled.
This goes through:
`
if (table.lookup(magentomodule_config, "allow_super_users_during_maint", "0") == "1" &&
        !req.http.Fastly-Client-Ip ~ maint_allowlist &&
        !req.url ~ "^/(index\.php/)?suadmin/" &&
        !req.url ~ "^/pub/static/") {

`
And should be:
`
if (table.lookup(magentomodule_config, "allow_super_users_during_maint", "0") == "1" &&
        !req.http.Fastly-Client-Ip ~ maint_allowlist &&
        !req.url ~ "^/(index\.php/)?suadmin/" &&
        !req.url ~ "^/pub/(static|error)/") {
`
This way we can use the same files in the maintenance of magento and in the maintenance of fastly.

**Comment by vvuksan** [comment]
Fixed here https://github.com/fastly/fastly-magento2/commit/ca4b05a7fdd5a5667bdd5f6e72380d1ce27adaf0.

Will go out as 1.2.188.

**Comment by marquesdevopen** [comment]
Sorry, forgot to update the issue.

The change should be:
`^(\/pub\/|\/)(static|error)\/`

Since in magento, the error directory is in the root of the project.
