### ISSUE TITLE
Store custom VCL snippets in Git?

### ISSUE THREAD

**Issue by oehmiche** [fastly/fastly-magento2#576]
In the documention for custom VCL snippets [there is a section for automated custom VCL snippets deployment](https://github.com/fastly/fastly-magento2/blob/master/Documentation/Guides/CUSTOM-VCL-SNIPPETS.md).

We did add our custom snippet `deliver_100_setHttpResponseHeaderXContentTypeOptionsNosniff.vcl` to our git repository - below the path `var/vcl_snippets_custom`.

After performing a deployment to our cloud-environment we expected to find the custom snippet on the server below `~/var/vcl_snippets_custom`.
But the file wasn't there. 

Why?

P.S. We are using Adobe Commerce Cloud v2.4.4 - with the fastly extension 1.2.185

**Comment by dpotkoc** [comment]
@oehmiche currently this is not supported by Adobe Cloud deployment process. We are working on solution.

**Comment by oehmiche** [comment]
@dpotkoc thank you for your quick reply. - Perhaps you can add this clarification to the documentation ;-) 
I close this ticket, since I am fine with the answer.
