### ISSUE TITLE
Fastly GeoIP with multi websites does not redirect properly.

### ISSUE THREAD

**Issue by atokarczyk** [fastly/fastly-magento2#580]
Hello,
recently I have updated magento into 2.4.4 version. I am using Fastly, it was also updated. After upgrade it is in version: **1.2.183**

After upgrade I have noticed, that redirection options for GeoIP configuration does not work as expected. After some debug I was able to find the problem, but I am not sure if provided modfications on Fastly module are intended or it is a BUG?

**Steps to reproduce:**
1. Magento installed with minimum 2 Websites configured
2. Fastyle Enabled and configured for GeoIP
3. Mapping for GeoIP with default redirect
4. One domain configured to use for whole store
5. Add store_code to url in Stores -> Configuration -> General -> Web

**Current result:**
When user comes from an IP that is from different language then default store it is redirected to a DEFAULT redirection configuration ('*')

**Expected result:**
Redirect user to the store according to mapping on Admin BackOffice (Stores -> Configuration -> Advanced -> System -> FPC -> Fastly Settings -> Advanced Configuration

Here is my example mapping:
![image](https://user-images.githubusercontent.com/10808956/196604706-6a33db72-2e40-4f9f-9856-ecd0b7ef53f5.png)

US store is a diferent WEBSITE (I have 2 Websites configured). Default store is and EU one in FR language. There is one main domain for all stores, only store_code is added to the url to distinct stores versions.

If a user that comes from USA for example will try to visit the store, he will be redirected to the "*" store, so EU one instead of the US version.

I did some look on the code and I have found that logic that match stores mapping have a condition that prevents proper mapping in case of multistore mappings.

Original code looks like this:
```
private function extractStoreForCurrentWebsite(array $map, string $countryCode): int
    {
        $store = $this->storeManager->getStore($map['store_id']);
        $website = $this->storeManager->getWebsite();
        if ($store->getWebsiteId() === $website->getId()
            && strtolower(str_replace(' ', '', $map['country_id'])) === strtolower($countryCode)) {
            return $store->getId();
        }
        return 0;
    }
```
    
    if you will look at the **IF** condition, you will notice that if you will match a store from different website, then **$store->getWebsiteId() === $website->getId()** condition will fail and "0" will be returned. so user will not be redirected to the proper store.
    
    Additionally match method looks currently like that:
    
```
private function extractMapping(string $mapping, string $countryCode): ?int
    {
        ...

        try {
            foreach ($extractMapping as $map) {
                if (!is_array($map) || !isset($map['country_id']) || !isset($map['store_id'])) {
                    continue;
                }
                if ($storeId = $this->extractStoreForCurrentWebsite($map, $countryCode)) {
                    return $storeId;
                }

                if ($storeId = $this->extractStoreForCurrentWebsite($map, '*')) {
                    return $storeId;
                }
            }
            return null;
        } catch (\Exception $e) {
            return null;
        }
    }
```
    here if you come from US country, and have in Mapping FR for example, then in foreach you will fail on first "extractStoreForCurrentWebsite", second if for "*" will be matched and returned to the user. I suppose this "*" should be as a fallback in case if you do not match. I have looked on previous version that we were using on magento 2.3.5, and this 2 methods were looking differently and was working fine.
    
    Not sure if this is intended or a bug maybe?
    
    I had to patch those 2 methods on my side to make it work in "previous" way, but maybe you know that problem and fixed it already?
    
    Regards.

**Comment by vvuksan** [comment]
Thanks for reporting. We are looking into it.
