### ISSUE TITLE
Expecting 404 on images that do no exist, but getting placeholder image instead

### ISSUE THREAD

**Issue by kavingas** [fastly/fastly-magento2#591]
### Prerequisites:

Adobe Commerce 2.4-develop with Fastly least 

### Steps to reproduce:
- Enable Fastly deep image optimization.
![image](https://user-images.githubusercontent.com/57118500/204439266-86e8416b-6436-4b33-acc8-39f5ba970cef.png)
- Access a random URL under the media directory.
E.g 
<site-url>/media/test.jpeg
- Observe the 404 response code
- Wait for 1 hour
- Make the same request again
- Observe 200 response code

(on) Screen recording https://shared-assets.adobe.com/link/0b4964de-3838-4e40-5428-fe8eb1433d2d

### (x) Actual result:
After 1 hour from the initial request, all the requests made to the media directory return the 200 status code with a placeholder image.

### (/) Expected result:
None existing images should respond with the 404 status code. 

#### (i) extra details
The default Adobe Commerce execution process gets interrupted when the deep image optimization is enabled.
https://github.com/fastly/fastly-magento2/blob/master/Plugin/MediaStorage/App/AroundMedia.php#L67

**Comment by vvuksan** [comment]
Fixed in 1.2.194.
