### ISSUE TITLE
It is not possible to remove GraphQL modules

### ISSUE THREAD

**Issue by dmanners** [fastly/fastly-magento2#596]
As with a lot of community members we remove the graphql modules as we are not actively using graphql. We do this for 2 reasons. 1. To remove the graphql endpoint itself, 2. to de-bloat the software as a whole.

To do this we use the composer replace option. e.g.

```
"replace": {
        "magento/module-graph-ql": "*",
        "magento/module-graph-ql-cache": "*"
}
```

After a composer install and setup:upgrade these modules will be removed but the fastly module will fail on set:di:compile as it cannot find the second parameter in the class `Fastly\Cdn\Plugin\GraphQl\AfterRenderResult` which is `Magento\GraphQlCache\Model\CacheableQuery`.

It is not possible just to disable this plugin but instead we have had to remove the full class via a .patch file.

In an ideal world there would be multiple modules for fastly one for the main system and one specific for graphql that we could then remove as well as the other graphql module.

**Comment by orkuncv** [comment]
We also run into this problem..
I totally agree with @dmanners solution, to separate the main fastly module and a graphql module.
