### ISSUE TITLE
Errors during di:compile

### ISSUE THREAD

**Issue by anvanza** [fastly/fastly-magento2#6]
I receive the following error while running the setup:di:compile command:

`/var/www/magento# php bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 6/7 [========================>---]  85% 2 mins 228.0 MiB                                       Errors during compilation:
	Fastly\Cdn\Controller\GeoIP\GetAction
		Incorrect dependency in class Fastly\Cdn\Controller\GeoIP\GetAction in /var/www/magento/vendor/fastly/magento2/Controller/GeoIP/GetAction.php
\Magento\Framework\UrlInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Fastly\Cdn\Controller\GeoIP\GetAction
		Incorrect dependency in class Fastly\Cdn\Controller\GeoIP\GetAction in /var/www/magento/vendor/fastly/magento2/Controller/GeoIP/GetAction.php
\Magento\Framework\UrlInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Fastly\Cdn\Controller\GeoIP\GetAction
		Incorrect dependency in class Fastly\Cdn\Controller\GeoIP\GetAction in /var/www/magento/vendor/fastly/magento2/Controller/GeoIP/GetAction.php
\Magento\Framework\UrlInterface already exists in context object
Total Errors Count: 1`

**Comment by phoenix-bjoern** [comment]
@anvanza Thanks for the report. Please check the latest commit, should be fixed in v1.0.4.
