### ISSUE TITLE
GeoIP bypass for Search Bots

### ISSUE THREAD

**Issue by nvorhees** [fastly/fastly-magento2#611]
When using Fastly's GeoIP redirection functionality, search index bots are also redirected. This has huge impacts in search engine rankings for sites with GeoIP enabled.  

Typically GeoIP redirection implementations will have various methods of specifying which requests to ignore for redirection, using things like IP ranges, or user-agent headers.

**Comment by vvuksan** [comment]
We do provide a way for users to modify the redirection based on their own requirements.

https://github.com/fastly/fastly-magento2/blob/master/Controller/GeoIP/GetAction.php

https://github.com/fastly/fastly-magento2/blob/master/view/frontend/templates/geoip/redirect.phtml
