### ISSUE TITLE
Cache purge by tag does not work

### ISSUE THREAD

**Issue by kavingas** [fastly/fastly-magento2#621]
## Prerequisites:

Adobe Commerce 2.4.6

### Steps to reproduce:
- Configure Fastly
- Create a product
-  Open the product from the front and refresh the page multiple times to make it cached
- Check the Cache header to confirm the page is cached
- Open the product from the backend and update the product price
- The indexer mode is set to update on save by default, the changes should be reflected in the front without CRON run. 
- Refresh the product page

### (x) Actual result:
The updated product price is not reflected in the frontend

### (/) Expected result:
The product price should be updated on the frontend

### (i) Observations
When cleaning the cache by tag it uses the tags as "tags":["cat_p_1"] but on the front page it sets the cache tag like p1

Internal ticket reference https://magento.zendesk.com/agent/tickets/613804

**Comment by vvuksan** [comment]
What happens if you reload the page for the second time? Does the correct
price show ?

**Comment by baudeval** [comment]
Hi, i have the same bug effectively when i reload for the second time the age of page return to 0 and the data is updated. But why it is necessary to reload the page 2 times ?

load entity page
update entity in back -> trigger clean_cache_by_tags
reload  the page entity contains data not uptodate and the page age is not reset
reload all is OK

**Comment by vvuksan** [comment]
This is the expected behavior due to a feature called Soft Purge. It's there to speed up the site so when a page is invalidated it's not actually removed from cache but served on subsequent request while new version of the page is retrieved in the background. If you do not want that behavior you will need to turn of Soft Purge in the Advanced configuration.

**Comment by baudeval** [comment]
@vvuksan thanks for reply
