### ISSUE TITLE
Add custom header for maintenance mode 503 response

### ISSUE THREAD

**Issue by nickkpsh** [fastly/fastly-magento2#637]
Hello, This is a follow-up to #468 

> When monitoring for uptime, there are typically 2 situations that return 503. 
> Either the origin is unavailable or the site is in maintenance mode.
> When enabling maintenance mode through the Magento Cloud CLI, php bin/magento maintenance:enable it creates a file var/.maintenance.flag which can be used by some monitoring tools.
> 
> When enabling maintenance mode via the Magento CLI for Fastly, php bin/magento fastly:maintenance -e (or via the UI) there is no flag file created.
> 
> Adding a custom header response would enable http monitoring to detect maintenance mode and prevent false positives for outage monitoring.
> (or, create the file var/.maintenance.flag on enable and delete on disable)

The solution proposed by @smaeda-ks would be perfect, is it possible to have this included in the next release?

```diff
diff --git a/etc/vcl_snippets/deliver.vcl b/etc/vcl_snippets/deliver.vcl
index 3809bd3..455a0d0 100644
--- a/etc/vcl_snippets/deliver.vcl
+++ b/etc/vcl_snippets/deliver.vcl
@@ -40,6 +40,9 @@
     # Add an easy way to see whether custom Fastly VCL has been uploaded
     if ( req.http.Fastly-Debug ) {
         set resp.http.Fastly-Magento-VCL-Uploaded = "1.2.165";
+        if (table.lookup(magentomodule_config, "allow_super_users_during_maint", "0") == "1") {
+            set resp.http.Fastly-Magento-Maintenance-Mode = "on";
+        }
     } else {
         remove resp.http.Fastly-Module-Enabled;
         remove resp.http.fastly-page-cacheable;
```

Thank you

**Comment by nickkpsh** [comment]
Just a quick update to say we have made a workaround to achieve what we wanted by reading the Edge Dictionaries

**Comment by vvuksan** [comment]
Response header has been added. It will go out with 1.2.207.
