### ISSUE TITLE
Unable to delete the backend settings

### ISSUE THREAD

**Issue by desaiuttam** [fastly/fastly-magento2#654]
Hello,

We are facing an issue with backend settings, we have added one test backed setting and tried to delete that but it's not working.

It's showing as the below error.

Failed to validate service version: Warning: Unused table `magentomodule_basic_auth` at: (input Line 12251 Pos 7) table magentomodule_basic_auth { ------########################-- Warning: Unused acl `admin_allow` at: (input Line 12256 Pos 5) acl admin_allow { ----###########-- Warning: Unused acl `allowlist` at: (input Line 12285 Pos 5) acl allowlist { ----#########-- Warning: Unused table `product_id_table` at: (input Line 12370 Pos 7) table product_id_table { ------################-- Undefined `backend F_O_TEST` at: (input Line 16861 Pos 23) set req.backend = F_O_TEST; ----------------------#########-

**Comment by ivanviduka** [comment]
Hello @desaiuttam can you please provide some information.

1) What version of Magento and PHP are you using?
2) How did you upload your backend settings? Was it from Magento Admin and if yes, can you provide what was your input?
3) Did you change anything in the meantime before deletion?
4) Where did this error occur or show?

I tried to reproduce problem locally, but I was able to create the backend and delete it right away, so additional information would be helpful.

**Comment by vvuksan** [comment]
Hi @desaiuttam 

Judging by the error message about an Undefined backend you may have referred to the backend you are trying to delete in custom VCL which is resulting in VCL validation errors. Did you add any custom VCL snippets ?
