### ISSUE TITLE
Vary Cookie reason

### ISSUE THREAD

**Issue by drpayyne** [fastly/fastly-magento2#678]
Hello, a lot of documents and resources online recommend not using `Vary:Cookie` as that will cause a very low cache hit ratio. From what I see, https://github.com/fastly/fastly-magento2/blob/master/etc/vcl_snippets/deliver.vcl#L30 does this. I'm not an expert, so I'd like to know what the reasoning behind this is, please. Thank you.

**Comment by vvuksan** [comment]
Hi Adarsh

That Vary is only sent to the end user/browser. It doesn't affect CDN
caching and it only affects browser cache.

**Comment by drpayyne** [comment]
Thank you for your response, @vvuksan. Appreciate it. I'll close this issue then as it was a misunderstanding from my side.
