### ISSUE TITLE
Bug on Fastly module UI

### ISSUE THREAD

**Issue by ikhadka** [fastly/fastly-magento2#682]
Hello Fastly Team, 

Multiple customers are raising this issue as a bug. 

Unable to add log shipping jobs due to a bug on Fastly Magento UI that is not saving 

When we add the condition and create it is not saving. 

Steps to Reproduce: stores>configuration> advanced > system > tools> attach condition  > create new response condition> name and give logic > click create > create go back onto it condition is missing

Customer is on the following fastly module version: 

1.2.210

Please note this issue is with fastly module so please investigate this from your side. 

Customer is on 
![fastly magento issue (2)](https://github.com/fastly/fastly-magento2/assets/111860779/7f322f97-6a4d-40fb-bbe7-e7e6b9b0b04a)

Thanks 
Ishwar

**Comment by dpotkoc** [comment]
Hello @ikhadka I will really appreciate if you can test PR https://github.com/fastly/fastly-magento2/pull/683

Thnx in advance

**Comment by ikhadka** [comment]
Hello @dpotkoc 

Thanks Sure I will request fastly team to test this. 

Thanks 
Ishwar

**Comment by ikhadka** [comment]
Hello @dpotkoc 

Just wondering have you pushed the change to a new fastly module version ? 

Thanks 
Ishwar

**Comment by vvuksan** [comment]
Hi @ikhadka,

We have not merged this request. If you are able to confirm that this fix works we can merge it immediately.

Thanks

**Comment by ikhadka** [comment]
Hello @vvuksan @dpotkoc 

Thank you for looking in to to this and we have tested this new code and this works. Please could you push the change to live. Also do let me know the module version customer needs to upgrade to see the new change Thanks

**Comment by vvuksan** [comment]
Fixed in 1.2.211.
