### ISSUE TITLE
GEOIP redirection causes 404 on specific cases

### ISSUE THREAD

**Issue by victoradobe** [fastly/fastly-magento2#693]
The GeoIP redirect functionality redirects customers to a specific store based on his Geolocation. The problem is that sometimes, the customer is redirected to a page that doesn't exist if the url contains the "store_code" but doesn't have a "/" in the end.

### Pre-requisites to reproduce:

1. Clean Magento instance with at least 2 store views
    1.1 Example: I'm using 2 store views (en and fr)
![image](https://github.com/fastly/fastly-magento2/assets/117451302/81085e8e-f928-4533-951d-15e53f0103dd)
2. Configure store to add store codes to the url (Stores -> Configuration -> General -> Web -> Url Options -> Add Store Code to URLS):
![image](https://github.com/fastly/fastly-magento2/assets/117451302/3b6c3ab7-eceb-4396-aff4-a1ce964c2f45)
3. Configure Fastly (Stores -> Configuration -> Advanced -> System -> Full Page Cache -> Caching Application):
![image](https://github.com/fastly/fastly-magento2/assets/117451302/9a694e27-c050-4564-aad6-307c601befef)
4. Configure GeoIP redirect (Stores -> Configuration -> Advanced -> System -> Full Page Cache -> Caching Application -> Fastly Configuration -> Advanced Configuration -> GeoIP Country Mapping):
![image](https://github.com/fastly/fastly-magento2/assets/117451302/914f3f21-6841-420c-834f-8a9c0a7739c5)

### Steps to reproduce: 

1. On a incognito tab, access the store front using a code that is not from your geolocation
    1.1 Ex: You're from EN, access the other storeview https://store-test.com/fr/
2. You'll see the dialog to tell about the redirection
3. Now, close all incognito tabs and open a new one
    3.1 Access the other storeview again, but now remove the last "/":  https://store-test.com/fr

### Expected Results 
Customer is redirected to the other storeview and sees the homepage

### Actual results
Customer will be redirected to the other store but the url will be something like:
https://store-test.com/en/en instead of just https://store-test.com/en/ (notice the extra "en" code)

### Additional info

It seems that the error originates on Fastly\Cdn\Block\GeoIp class:
![Screenshot 2024-04-03 at 15 14 22](https://github.com/fastly/fastly-magento2/assets/117451302/8537c563-5657-4bc6-b0d3-5c92cc952c06)

Maybe a check could be done to add an extra "/" to end of the url if there isn't one, or remove all paths completely.

**Comment by ikhadka** [comment]
@dpotkoc  Please could you take a look at this.

Thanks 
Ishwar

**Comment by dpotkoc** [comment]
@victoradobe in this moment, we are still trying to reproduce issue but without success.

For geoip redirection we are using varnish esi include tag.

I configured the same environment (as you explained) but I can't get error. 
This is what I got:

![fastly esi hole](https://github.com/fastly/fastly-magento2/assets/553247/67fd4e27-709e-4782-aa03-05fcff2df848)

You can see that I got redirect url: "redirect_url": "http://fastlyee.lo/en/stores/store/switch/?___from_store=fr&___store=en",


Please can you provide me result of your esi include, I would like t see what you are getting.


Thnx
Domagoj

**Comment by dpotkoc** [comment]
@victoradobe I reproduced issue. Tnx for reporting.

We are working on fix.

Domagoj
