### ISSUE TITLE
ReflectionException

### ISSUE THREAD

**Issue by toonvd** [fastly/fastly-magento2#7]
I get the following error on a clean install of Magento 2.0.7:
                                                                      
  [ReflectionException]                                               
  Class Fastly\Cdn\Console\Command\GenerateVclCommand does not exist

This is right after enabling the extension on cache:flush

**Comment by phoenix-bjoern** [comment]
@toonvd Are you in production or developer mode? If you are in production please make sure you have compiled the code.
Please also verify the class (https://github.com/fastly/fastly-magento2/blob/master/Console/Command/GenerateVclCommand.php) exists locally.

**Comment by anvanza** [comment]
This could be solved by #11

**Comment by phoenix-bjoern** [comment]
#11 has been merged so this issue should be fixed as well.
