### ISSUE TITLE
Unable to save Fastly configuration - the screen just scrolls to the top

### ISSUE THREAD

**Issue by yyevgenii** [fastly/fastly-magento2#72]
Hi.

I've found a bug in fastly-magento2-1.2.12 and later versions: you can't save configuration in Magento admin backend, the save button doesn't work anymore. The 1.2.11 works fine.

Steps to reproduce:
1. install magento
2. install fastly-magento2-1.2.12 (or newer)
3. login into admin backend
4. go to System > Configuration > System
5. under Full Page Cache, set Caching Application = Fastly CDN
6. Enter the Fastly settings (you can enter whatever you want, it doesn't matter)
7. Click on "Save" at top right corner

Expected result: configuration will be saved and page will be reloaded
Actual result: nothing happens when you click on "Save" button, but the page scrolls to the top instead

If you need some other information let me know.

**Comment by vvuksan** [comment]
Hi @yyevgenii this has been fixed in version 1.2.13. Thanks for reporting.
