### ISSUE TITLE
Datadome edge module not up-to-date

### ISSUE THREAD

**Issue by idembele-datadome** [fastly/fastly-magento2#725]
Hello, 

We’re debugging an issue with a new Datadome edge module deployment.

While reviewing the generated VCL, we noticed that an older version of the module was deployed instead of the expected one.
We were expecting Datadome module version [2.23.0](https://github.com/fastly/fastly-magento2/pull/715), but version 2.13 was deployed  instead.

**Steps to reproduce**
1. Be on Fastly/Magento version 1.2.211
2. Enable required Pragma as per Datadome [documentation](https://docs.datadome.co/docs/module-fastly#prerequisites)
3. Enable Datadome Edge module
4. Configure Datadome edge module and upload
5. Download generated VCL last version

**Expected Outcome**
- VCL should be updated with the latest Datadome Edge module (v2.23.0)
- Datadome Should start  processing requests

**Actual Outcome**
Old version of Datadome edge module is deployed (2.13)

Any guidance would be greatly appreciated!
Thanks so much for your help! (

**Comment by idembele-datadome** [comment]
hi @rcaril 

thanks for your response.
- we update fastly/magento to it latest 
- we disable Datadome and re enable it  and upload the VCL
- we check the version deployed and it was the latest (2.23).

Thanks a lot

**Comment by rcaril** [comment]
Great, glad to hear it!
