### ISSUE TITLE
Install from zip file shows error on setup:upgrade

### ISSUE THREAD

**Issue by jondade** [fastly/fastly-magento2#8]
The error displayed is:

`[Exception]
  Notice: Undefined index: Magento\PageCache\Model\Config in /var/www/html/vendor/magento/framework/Interception/PluginList/PluginList.php on line 232`

**Comment by phoenix-bjoern** [comment]
@jondade found a way to work around this magento 2.1 core bug which maybe only occurs in developer mode.
