### ISSUE TITLE
Cannot purge Fastly cache in 1.2.16

### ISSUE THREAD

**Issue by yyevgenii** [fastly/fastly-magento2#80]
There's a bug in fastly-magento2-1.2.16: I'm unable to clean Fastly cache by store or by content type from Magento admin backend. I'm getting the message: "The purge request was not processed successfully." Quick Purge (clean cache by URL) works fine. I can't reproduce this issue on version 1.2.15, so the bug is only in fastly-magento2-1.2.16.

Steps to reproduce:

install fastly-magento2-1.2.16
configure fastly (ID and token)
go to System > Tools > Cache Management
click on "Clean Fastly CDN by content type" or "Clean Fastly CDN by store"

Expected result: cache will be successfully purged and I'll get the message "The Fastly CDN has been cleaned."
Actual result: cache isn't cleaned and I get the message "The purge request was not processed successfully."

If you need some other information let me know.

**Comment by vvuksan** [comment]
Fixed in 1.2.17 of the plugin. We'll release shortly.
