### ISSUE TITLE
Adding fastly/magento2 causes "Area code not set" error

### ISSUE THREAD

**Issue by bryanjswift** [fastly/fastly-magento2#90]
**System Information**

* OS name and version: Debian 8 (Jessie)
* PHP version: PHP 7.0.20-1~dotdeb+8.1 (cli) ( NTS 
* Database server name and version: 5.7.18 MySQL Community Server (GPL)
* Magento version: 2.1.7 EE
* Composer version: Composer version 1.4.1 2017-03-10 09:29:45
* Description of the problem. What is happening that shouldn't: Error when running `php ./bin/magento setup:upgrade` after requiring the fastly/magento2 module.
* Description of the expected behavior: `php ./bin/magento setup:upgrade` should complete without error.

Exact steps to reproduce the error:

1. Check out a commit
1. Cleaning caches (including generated files/classes)
1. exec `composer config repositories.fastly-magento2 git "https://github.com/fastly/fastly-magento2.git"`
1. exec `composer require fastly/magento2`
1. exec `composer install` (to insure other dependencies match the new commit)
1. exec `php ./bin/magento setup:upgrade -vvv`

    [Magento\Framework\Exception\SessionException]                                                                        
    Area code not set: Area code must be set before starting a session.

    [Magento\Framework\Exception\LocalizedException]
    Area code is not set

The full stack trace is:

    Exception trace:
     () at /srv/example.com.local/vendor/magento/framework/App/State.php:139
     Magento\Framework\App\State->getAreaCode() at /srv/example.com.local/vendor/magento/framework/Session/SessionManager.php:173
     Magento\Framework\Session\SessionManager->start() at /srv/example.com.local/var/generation/Magento/Framework/Session/Generic/Interceptor.php:50
     Magento\Framework\Session\Generic\Interceptor->start() at /srv/example.com.local/vendor/magento/framework/Session/SessionManager.php:130
     Magento\Framework\Session\SessionManager->__construct() at /srv/example.com.local/var/generation/Magento/Framework/Session/Generic/Interceptor.php:14
     Magento\Framework\Session\Generic\Interceptor->__construct() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
     Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:89
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /srv/example.com.local/vendor/magento/framework/ObjectManager/ObjectManager.php:71
     Magento\Framework\ObjectManager\ObjectManager->get() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
     Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /srv/example.com.local/vendor/magento/framework/ObjectManager/ObjectManager.php:71
     Magento\Framework\ObjectManager\ObjectManager->get() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
     Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /srv/example.com.local/vendor/magento/framework/ObjectManager/ObjectManager.php:71
     Magento\Framework\ObjectManager\ObjectManager->get() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
     Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /srv/example.com.local/vendor/magento/framework/ObjectManager/ObjectManager.php:71
     Magento\Framework\ObjectManager\ObjectManager->get() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
     Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /srv/example.com.local/vendor/magento/framework/ObjectManager/ObjectManager.php:71
     Magento\Framework\ObjectManager\ObjectManager->get() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
     Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /srv/example.com.local/vendor/magento/framework/ObjectManager/ObjectManager.php:71
     Magento\Framework\ObjectManager\ObjectManager->get() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
     Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /srv/example.com.local/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
     Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /srv/example.com.local/vendor/magento/framework/ObjectManager/ObjectManager.php:57
     Magento\Framework\ObjectManager\ObjectManager->create() at /srv/example.com.local/setup/src/Magento/Setup/Model/Installer.php:931
     Magento\Setup\Model\Installer->createSchemaDataHandler() at /srv/example.com.local/setup/src/Magento/Setup/Model/Installer.php:1245
     Magento\Setup\Model\Installer->getSchemaDataHandler() at /srv/example.com.local/setup/src/Magento/Setup/Model/Installer.php:841
     Magento\Setup\Model\Installer->handleDBSchemaData() at /srv/example.com.local/setup/src/Magento/Setup/Model/Installer.php:796
     Magento\Setup\Model\Installer->installDataFixtures() at /srv/example.com.local/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php:74
     Magento\Setup\Console\Command\UpgradeCommand->execute() at /srv/example.com.local/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
     Symfony\Component\Console\Command\Command->run() at /srv/example.com.local/vendor/symfony/console/Symfony/Component/Console/Application.php:874
     Symfony\Component\Console\Application->doRunCommand() at /srv/example.com.local/vendor/symfony/console/Symfony/Component/Console/Application.php:195
     Symfony\Component\Console\Application->doRun() at /srv/example.com.local/vendor/magento/framework/Console/Cli.php:96
     Magento\Framework\Console\Cli->doRun() at /srv/example.com.local/vendor/symfony/console/Symfony/Component/Console/Application.php:126
     Symfony\Component\Console\Application->run() at /srv/example.com.local/bin/magento:23

**Comment by tnikcevs** [comment]
Hello

I've tried and failed to replicate the issue with steps you provided both in developer and production mode. 
Also I cannot see anything related to Fastly in stack trace, have you tried removing the module completely and executing upgrade? 

Additionally, stack trace looks like there are schema issues that cause this. Have you tried removing the Setup directory from Fastly module and run the upgrade on testing environment to see if error persists? If not, please try and let me know if the error showed again.

Just to make sure, have you tested this on clean Magento version with just Fastly module installed?

Regards,
Tomislav

**Comment by bryanjswift** [comment]
I just tested by removing the `vendor/fastly/magento2/Setup` directory to a temporary location and then executing the `setup:upgrade` task. `setup:upgrade` completes successfully with the `vendor/fastly/magento2/Setup` directory removed. If I move it back and re-run `setup:upgrade` task execution succeeds because the fastly setup is skipped as the run without a `Setup` directory created the an entry in the `setup_module` table.

I realized I didn't previously include I am using Magento 2.1.7 Enterprise Edition, I don't know if that will matter over testing with Community Edition.

**Comment by tnikcevs** [comment]
This is only meant to be for testing, upgrade scripts contain part of needed data for module so make sure you revert changes by removing Fastly_Cdn from setup_module table and run upgrade again (after issue is resolved).

I will try it out on 2.1.7 EE and get back to you, hopefully I can reproduce the bug on EE.

**Comment by bryanjswift** [comment]
My team was able to resolve this by removing some other extensions. This appears to have been a dependency injection conflict between the Fastly module another module we had included in our code base. Specifically modules from https://www.mageworx.com. We had `MageWorx_CurrencySwitcher`, `MageWorx_CustomerLocation`, `MageWorx_GeoIP`, `MageWorx_GeoLock`, `MageWorx_StoreCurrencyMeta`, and `MageWorx_StoreSwitcher` installed. I do not know which of these specifically was causing the conflict as they have for now all been removed.

**Comment by tnikcevs** [comment]
I see, thank you for feedback regarding this.
Regards,
Tomislav
